### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by dakom** [leudz/shipyard#1]
Is it possible to add a sort functionality for packs and storages?

For comparison, it's available on [EnTT groups](https://skypjack.github.io/entt/classentt_1_1basic__group_3_01Entity_00_01get__t_3_01Get_8_8_8_01_4_00_01Owned_8_8_8_01_4.html#a0464e3b686015ec92dbf0efecc8bcbd6) as well as [EnTT storage](https://skypjack.github.io/entt/classentt_1_1basic__storage.html#ac1ed30f50fdc3eb2f994e3b4440dcf32) (there's another sort for storage too [comparing to entities](https://skypjack.github.io/entt/classentt_1_1basic__storage.html#aac84c253cdf3bf0357d6d729a7430635))

This could make it easier to impose something like a hierarchy... for example, a scene graph might be built via having Transform and Relationship components, and making a pack of those two. Then even if new entities are added, `sort()` could be called at just that time to keep the vector in a breadth-first order for quick traversal each tick.

**Comment by leudz** [comment]
The short answer is yes.

Thorough answer: Sorting entire pack or non packed storages should not be that complicated to implement but users will have to pass entire pack, like [add_component](https://docs.rs/shipyard/0.1.1/shipyard/trait.AddComponent.html).
Sorting packed storages but not the full pack isn't possible but a function sort_as_best_as_possible + a special iterator could result in pretty good iteration speed.
respect should be pretty easy to implement.
And of course some pack might not be sort-able (for example modified components). But sorted as best as possible should be possible in that case.

I also would like to have a sorted pack to keep components sorted and pay the cost at insertion/removal/modification.

**Comment by leudz** [comment]
ba652d23db33611b1375f770a167b85aa678e598 introduces basic sorting: single storage and packs.

**Comment by chrisburnor** [comment]
It might be valuable to think of this as an index on the storage.  There could even be multiple indices per storage or even indices across storages.  Generally, I'd imagine that the need for sorted storages would come from needing to iterate over sorted items many times (relative to the number of insertions).  For ad-hoc sorts, I don't see much advantage over just getting the collection and sorting it.

**Comment by leudz** [comment]
>  There could even be multiple indices per storage or even indices across storages

Why not, it could be a functionality but how would you tell the iterator to use these indices?
It could be part of an iterator blueprint maybe.

>  Generally, I'd imagine that the need for sorted storages would come from needing to iterate over sorted items many times (relative to the number of insertions)

Probably. I know it's what happens in the tutorial.

>  For ad-hoc sorts, I don't see much advantage over just getting the collection and sorting it.

If you're referring to sort on insert/... it'll be possible with events without me doing anything. So I'll let users decide if they need it or not.
