### ISSUE TITLE
Docs: Add example of serialization / deserialization with serde

### ISSUE THREAD

**Issue by jrmiller82** [leudz/shipyard#104]
Would be nice to see the idiomatic way to serialize/deserialize a world.

**Comment by leudz** [comment]
Currently the only (de)serializable type is `EntityId`.
You can implement storage (de)ser to a certain extent but it won't be pretty.
I'm working on #48 and post updates on zulip.

**Comment by jrmiller82** [comment]
Ahhh! I just assumed it was already working since the docs say serde is a Cargo.toml feature to turn on.

**Comment by leudz** [comment]
I'm closing it, there will be a chapter on (de)ser in the guide and the tutorial for 0.5.
