### ISSUE TITLE
`Debug` implementation on `World`

### ISSUE THREAD

**Issue by OvermindDL1** [leudz/shipyard#108]
Would it be possible to add a `std::fmt::Debug` implementation to `shipyard::World` that just gives some basic information about the state of the world?  It's fine for it to run slow as it is only for debug information but it would be useful to be able to just derive Debug onto parent structures.

**Comment by leudz** [comment]
Sure! What do you have in mind for the info?
Something like a list of types with how many components they have and a list of workloads maybe?
It'll probably look like a stripped down version of #84

**Comment by OvermindDL1** [comment]
Ah, adding the memory information would be perfect to add to it!

Just in general anything that would be generically useful to see for random debug sessions, so whatever you might run across, though I'd keep it to less than a hundred lines.  ^.^

**Comment by leudz** [comment]
Alright, so I'll try to make the `Debug` implementation as useful as possible without making it too verbose and the [alternate](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.alternate) will have the full memory report.
It doesn't seem too complicated, I might do it soon but I only promise to do it by 0.5 release.

Thanks for the suggestion =)

**Comment by OvermindDL1** [comment]
Sounds awesome!

All good, I'm using the git version anyway, making a mini-game (on top of ggez, of which I keep running in to issues, so I might change to piston, but eh...) for the purpose of learning shipyard in depth so as it's a learning project then grabbing latest is good for me as I'm good with fixing things as they break.  :-)

**Comment by leudz** [comment]
If you encounter any problem don't hesitate, even in the learning materials or doc.

About piston I don't have a personal opinion but I saw this in the gamedev discord yesterday:
> StygianLightning
don't use piston

> NixieTube
why?

> cwfitzgerald
abandonware mainly

> StygianLightning
^

**Comment by OvermindDL1** [comment]
`ggez` is mainly abandonware too, and amethyst doesn't run yet on vulkan-less systems last I checked, lol, so I'm kind of stuck...  ^.^;

But yep, I will post issues if I find anything odd or a better way of doing something or so.  My ECS did outperform shipyard in 'some' cases (and on par the rest of the time) so I might try to figure out why and see if I can either mention how to fix it here or PR it.
