### ISSUE TITLE
Publicize `SparseSet`

### ISSUE THREAD

**Issue by OvermindDL1** [leudz/shipyard#109]
I'm trying to use a SparseSet to hold value-specific entity mappings for a reverse mapping (this would be a useful pattern to bake into `shipyard` somehow though, I use it quite a lot in a few specific situations), at the very least it would be useful to make using `SparseSet` fully `pub`lic so we could `new` our own instances of it and manage them as we have need.

**Comment by leudz** [comment]
`SparseSet` (likely a newtype of it) becoming public is part of the custom storage feature.
I'm pretty sure I'll have to make a different type, for example `insert` can't be public but you would need it of course.

Could you show me a small example of reverse mapping, I want to make sure I correctly understand what you mean.

**Comment by OvermindDL1** [comment]
It's just a holder of EntityId's in a sparse area, order isn't important in the individual cells just grabbing a cell let's me look up all associated EntityId's quickly.  Think like an octree (though different in this case, more of an r-tree).

**Comment by leudz** [comment]
```rust
struct SparseSet<T> {
    sparse: SparseArray<[usize; BUCKET_SIZE]>,
    dense: Vec<EntityId>,
    data: Vec<T>,
}
```

I don't think `sparse` and `dense` type will be customizable, if you need them to be what I'll export for 0.5 won't be enough.

**Comment by OvermindDL1** [comment]
I don't need them to be that no, I just use it as a set, no order expected, etc...

**Comment by leudz** [comment]
`SparseSet` has become more and more special and when packs come back it won't be a true `SparseSet` anymore.
While I still agree it'd be nice to have a `SparseSet` crate I don't think it should be the one implemented here.

There is one on [crates.io](crates.io) if someone reading this is looking for one.
