### ISSUE TITLE
Unable to `iter` a tuple of view's

### ISSUE THREAD

**Issue by OvermindDL1** [leudz/shipyard#110]
Using the git version of `shipyard`.

As per the docs at https://github.com/leudz/shipyard/blob/master/guide/src/fundamentals/iterators.md I tried to iterate over a tuple of views like:
```rust
for (_, coord) in (&selected, &coords).iter() {
```
However it's saying that there is no `iter` method on tuple's, specifically the full message is:
```rust
error[E0599]: no method named `iter` found for tuple `(&shipyard::view::View<'_, over_simple_game_1::core::map::coord::Coord>, &shipyard::view::View<'_, game::components::IsSelected>)` in the current scope
   --> src/testing_iteration/mod.rs:656:45
    |
656 |                     for (coord, _) in (&coords, &selected).iter() {
    |                                                            ^^^^ method not found in `(&shipyard::view::View<'_, testing_setup::core::map::coord::Coord>, &shipyard::view::View<'_, components::IsSelected>)`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use shipyard::iter::into_iter::IntoIter;`
```
And it's suggestion of `use shipyard::iter::into_iter::IntoIter;` does not work either because `shipyard::iter::into_iter` is not public.

**Comment by OvermindDL1** [comment]
Same issue holds on if I try to `iter` over just a direct view as well like `selected.iter()`.

**Comment by leudz** [comment]
Yep, you need the `IntoIter` trait but almost everything exported is at the root `shipyard::IntoIter`.
The guide should mention it, I'll add it.

**Comment by OvermindDL1** [comment]
If only the error message actually listed that, lol.

Have you thought about adding a `shipyard::prelude` module to just import everything that should be useful and not conflict with other things?  It's a common pattern many libraries use, just `use shipyard::prelude::*;` to bring in a 'default set' of useful things that won't conflict with other libraries.

That got it working though!  Curious why the compiler was suggesting something entirely different that was inaccessible...

**Comment by leudz** [comment]
There was a `prelude` in 0.3 but almost everything was in it so I decided to just move everything to the root.

Most types and traits are equally useful so having a `prelude` didn't make much sense.
In addition, if you have something local with the same name it will take precedence so conflicts should be fairly rare.

I think the compiler isn't smart enough to know the trait is re-exported and that you should use it from there. It just gives you its "full name".
