### ISSUE TITLE
Out of date references to the book

### ISSUE THREAD

**Issue by svenstaro** [leudz/shipyard#111]
The former book is now located here: https://leudz.github.io/shipyard/guide/ however the [tutorial](https://leudz.github.io/shipyard/tutorial/) and [docs frontpage](https://docs.rs/shipyard/0.4.1/shipyard/) still link to the old location of the book.

**Comment by leudz** [comment]
Thank you for letting me know.
I can't fix the link in the doc without publishing a new version and I don't want to publish a new version just to fix the links ^^

I didn't think of deprecating them however. This will be fixed soon.

**Comment by svenstaro** [comment]
I guess I'll just leave this open for the time being assuming you actually want to fix the references themselves as opposed to just duplicating the data to both locations.

That said, I'm really looking forward to the new version. Serialization support (and by extension, networking) would be really neat to have.

**Comment by leudz** [comment]
The plan is to yank 0.3 and 0.4 when 0.5 is released. There are a few issues with some iterators and with window creation.
Starting with this release there will be a guide per version plus a master guide so this problem shouldn't happen again.

I'm also excited about serialization. It wasn't easy to find a way to make it work but the result should be ok.

**Comment by svenstaro** [comment]
That sounds amazing. Looking forward to it.

**Comment by leudz** [comment]
With the release of 0.5.0 all links are now valid.
