### ISSUE TITLE
`Entities.try_add_component` consuming the storage

### ISSUE THREAD

**Issue by OvermindDL1** [leudz/shipyard#112]
`Entities.try_add_component` and `Entities.add_component` are consuming the `storage` that is passed in because they both call `storages.try_add_component` is a trait that is defined as:
```rust
pub trait AddComponent<T> {
    fn try_add_component(
        self,
        component: T,
        entity: EntityId,
        entities: &Entities,
    ) -> Result<(), error::AddComponent>;
    #[cfg(feature = "panic")]
    #[cfg_attr(docsrs, doc(cfg(feature = "panic")))]
    fn add_component(self, component: T, entity: EntityId, entities: &Entities);
}
```

In other words, it takes `self`, which moves the storage in, so we cannot use the storage again inside a `run`, which is bad when inserting a number of the same component on many entities among other issue.

In short, doing this:
```rust
			entities.add_component(storage, c, entity1);
			entities.add_component(storage, c, entity2);
```
Causes this error:
```rust
102 |         storage: &mut ViewMut<MapCoord>,
    |         ------- move occurs because `storage` has type `&mut shipyard::view::ViewMut<'_, core::map::coord::MapCoord>`, which does not implement the `Copy` trait
...
105 |             entities.add_component(storage, c, entity1);
    |                                    ------- value moved here
106 |             entities.add_component(storage, c, entity2);
    |                                    ^^^^^^^ value used here after move
```

How are you supposed to access a storage multiple times after adding components with it?

**Comment by leudz** [comment]
You can reborrow the view:

```rust
&mut *storage
```

Usually the compiler does it for you but not here probably because of `self`.

**Comment by OvermindDL1** [comment]
Correct, the `self` in the trait means it is taking full ownership of it, and since it is not Copy nor Clone then it consumes it, you cannot reborrow it because of that.

**Comment by OvermindDL1** [comment]
Ah, reborrowing it does work, thanks to the indirection of the intermediary function on Entities, even though `AddComponent` takes it as `self`.  Why do those traits consume it though?

**Comment by OvermindDL1** [comment]
Lol, well in that case is there any heavy copying going on due to `self` consuming single storages that aren't are reference inside a tuple?  Honestly I'd be fine with a tuple reference of references.  ^.^

**Comment by leudz** [comment]
The tuple is just a few references going from one stack to another, it should be negligible.

Just reading it "tuple reference of references", it seems evil xD
More seriously, to me it makes sense that when you have a single view you pass `&mut view` and when you have two you pass `(&mut view1, &mut view2)`.
With a tuple reference I would expect `&mut (view1, view2)` but that would consume the views to create the tuple.

**Comment by OvermindDL1** [comment]
Well if these are lightweight enough to just `Copy` around then can they be `Copy`?  ^.^

**Comment by leudz** [comment]
`Copy` has nothing to do with size in theory. Making exclusive references `Copy`/`Clone` would make it impossible to not alias them.
But that's all a Rust thing I have nothing to do with it =)

**Comment by OvermindDL1** [comment]
Referencing copy so in the functions that consume them then I could just 'copy' it in instead of moving it in.  It is feeling like it wants me to define functions by having them not be references, especially as the functions that use it are consuming it.

**Comment by leudz** [comment]
I understand that the move is confusing but I don't thing I can do better.

It makes the library consistent, `AddComponent` only takes exclusive views so in theory a `&mut self` is possible. That's not the case for `Get` since it can take both shared and exclusive views.

And it would only solve the issue for a single view since creating a tuple moves the values. [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=edbf15088d3ef553ce31e7fc8588be4b)

**Comment by OvermindDL1** [comment]
This still all seems to keep coming down to not wanting to accept a reference of a tuple of references, which will seems fine to me?
