### ISSUE TITLE
View/ViewMut (and probably others) `get` is not public

### ISSUE THREAD

**Issue by OvermindDL1** [leudz/shipyard#113]
Currently attempting to call `get` on a `View`/`ViewMut` storage (and probably other types) fails due it being `pub(crate)`, yet the `Index`/`IndexMut` implementations just call them straight, except they `.unwrap()` the value.  I can test with `.contains` first but that's just doing a double lookup needlessly.  Is there a reason that `.get` and so forth are not public even though `Index` lookups just call them and work fine other then they `.unwrap()` it?

**Comment by leudz** [comment]
`SparseSet::get` is private, you have to use the [`Get`](https://docs.rs/shipyard/0.4.1/shipyard/trait.Get.html) trait.
Indexing is a trait, not a method so even if I wanted to I couldn't make it private. But the real reason is indexing only woks with a single `SparseSet`.

**Comment by OvermindDL1** [comment]
Hmm, I tried calling `storage.get(entity_id)` but the compiler said it was private.  Is the Get trait not imported by default in `use shipyard::*;` or is the compiler just not liking the function name conflict because of `Deref`...

**Comment by OvermindDL1** [comment]
```rust
error[E0599]: no method named `try_get` found for struct `shipyard::view::View<'_, game::components::DrawSprite>` in the current scope
   --> src/game/mod.rs:855:38
    |
855 |                 if let Some(draw) = draw_sprites.try_get(entity) {
    |                                                  ^^^^^^^ method not found in `shipyard::view::View<'_, game::components::DrawSprite>`

error: aborting due to previous error; 3 warnings emitted
```
Yeah it's not even suggesting a `use` or anything...

**Comment by OvermindDL1** [comment]
Well `Get` is in scope, but even calling it straight fails:
```rust
error[E0191]: the value of the associated type `Out` (from trait `shipyard::get::Get`) must be specified
   --> src/game/mod.rs:855:25
    |
855 |                 if let Some(draw) = Get::try_get(draw_sprites, entity) {
    |                                     ^^^ help: specify the associated type: `Get<Out = Type>`

error[E0599]: no function or associated item named `try_get` found for trait object `dyn shipyard::get::Get` in the current scope
   --> src/game/mod.rs:855:30
    |
855 |                 if let Some(draw) = Get::try_get(draw_sprites, entity) {
    |                                          ^^^^^^^ function or associated item not found in `dyn shipyard::get::Get`

error: aborting due to 2 previous errors; 3 warnings emitted
```
The other error remains even when I add the `Out` type.

**Comment by OvermindDL1** [comment]
Doesn't work as a tuple either:
```rust
error[E0599]: no method named `try_get` found for tuple `(&shipyard::view::View<'_, game::components::DrawSprite>,)` in the current scope
   --> src/game/mod.rs:855:42
    |
855 |                 if let Some(draw) = (&draw_sprites,).try_get(entity) {
    |                                                      ^^^^^^^ method not found in `(&shipyard::view::View<'_, game::components::DrawSprite>,)`
```

**Comment by leudz** [comment]
`get` was removed in master and `try_get` is now simply `get`.

**Comment by OvermindDL1** [comment]
Ah, that compiles and works, though the IDE is unhappy about it as it thinks that `.get` is private...  ^.^;

**Comment by leudz** [comment]
I'll rename `SparseSet::get` to avoid this issue, with `private_get` or something like that it shouldn't be confused anymore (I hope ^^)

**Comment by OvermindDL1** [comment]
Any thought about removing the `Deref` and so forth and replace those with explicit `as_window` or so calls instead?  The `Deref` trait is generally only supposed to be used on things that are smart-pointer like, which things like View are not, instead they are a container style type.  In general I'm guessing that users shouldn't be accessing the window straight in the general case, and instead should be calling the calls directly on View/ViewMut/etc instead (which may of course delegate to the Window but eh).

**Comment by OvermindDL1** [comment]
As the official docs state at:  https://doc.rust-lang.org/std/ops/trait.Deref.html

> Because of this, `Deref` **should only be implemented for smart pointers** to avoid confusion.

Bolding is in the docs, it's very important to them.

**Comment by leudz** [comment]
A `View` is equivalent to a `RwLockReadGuard` and it implements `Deref` https://doc.rust-lang.org/std/sync/struct.RwLockReadGuard.html#impl-Deref.

`Deref` usage remains debated, some people go as far as to use it to mimic inheritance for example.
I use it in shipyard to have specialization.

I think it's a good usage here, as you say: "which may of course delegate to the Window". A `View` doesn't add anything useful, it's just there to release the lock. So functionality wise it's equivalent to what's inside.

**Comment by OvermindDL1** [comment]
Releasing a lock may be all it does, but conceptually it seems like a unique type, a safe "view" into the storage.  I guess the better comparison would be that when you deref a rwlock or smart pointer you get the contained type so it can, for example, be passed into other functions that expect that type rather than lock, how often does that happen for `View`?  How many functions expect a `Window` instead of a `View`?

**Comment by OvermindDL1** [comment]
Hmm, looking more closely:
```rust
pub struct View<'a, T> {
    window: Window<'a, T>,
    _borrow: Borrow<'a>,
    _all_borrow: Borrow<'a>,
}
```
So really all it does 'is' just handle the internal `window`, so that does actually sound fine for deref in this case...

So let's look at `Get`, it's implement on View, not on Window, as:
```rust
impl<'a: 'b, 'b, T: 'static> Get for &'b View<'a, T> {
    type Out = &'b T;
    fn try_get(self, entity: EntityId) -> Result<Self::Out, error::MissingComponent> {
        (**self).get(entity).ok_or_else(|| error::MissingComponent {
            id: entity,
            name: type_name::<T>(),
        })
    }
    fn get(self, entity: EntityId) -> Self::Out {
        self.try_get(entity).unwrap()
    }
}
```
(copying from the 0.4.1 docs rather than git master, but same idea)

So the conflict is because both a `get` on what `Deref` returns as well as a `get` on the `View` type implementation of `Get` itself.  I'm thinking the `Get` trait should perhaps be more on the Window/WindowMut type.  If View/ViewMut/etc are indeed supposed to essentially be like the return of `lock` on RWLock and so forth, then it shouldn't have much if anything implemented on it itself beyond Deref, implementations should be what is on the Deref'd type itself, so `Window` in the case of `View`.

**Comment by leudz** [comment]
You usually don't want `Deref` for types that add some property.
Like [`Wrapping`](https://doc.rust-lang.org/std/num/struct.Wrapping.html) for example, it can't implement `Deref<T>` because it makes all operation wrap.
`View` is fine, with your last message I think we agree on that point.

I agree that ideally `Get` would only be implemented on windows and `SparseSet` but the compiler has trouble with that.
For example I have this code in the guide:
```rust
world.run(|mut u32s: ViewMut<u32>, usizes: View<usize>| {
    let (i, &j) = (&mut u32s, &usizes).get(entity_id).unwrap();
    *i += j as u32;
    *i += j as u32;
});
```
If I remove the implementation on `View` it triggers an error on `&usizes`. You'd have to use `&*usizes` but that's not obvious.

Could you show me the code that has the conflicting implementation, I never had this problem.

**Comment by OvermindDL1** [comment]
It's not a conflict at compile-time but rather the IDE, I first hit it on this kind of code:
```rust
				let coords = all_storages.try_borrow::<View<MapCoord>>();
				let blah = coords.get(entity);
```
Which causes the IDE to red-squiggle the `get` saying that it is private.  That's what initially caused me to question that (since compiling takes a half a minute it's not something I do often).

The issue I hit in the other thread was where like this:
```rust

				let entities = all_storages.try_borrow::<EntitiesView>()?;
				engine.remove_coord_from_entity(entity, entities, all_storages.try_borrow()?)?;
				engine.set_entity_to_coord(entity, coord, entities, all_storages.try_borrow()?)?;
```
Which causes this compile error:
```rust
error[E0382]: use of moved value: `entities`
   --> src/game/mod.rs:233:48
    |
231 |                 let entities = all_storages.try_borrow::<EntitiesView>()?;
    |                     -------- move occurs because `entities` has type `shipyard::view::EntitiesView<'_>`, which does not implement the `Copy` trait
232 |                 engine.remove_coord_from_entity(entity, entities, all_storages.try_borrow()?)?;
    |                                                         -------- value moved here
233 |                 engine.set_entity_to_coord(entity, coord, entities, all_storages.try_borrow()?)?;
    |                                                           ^^^^^^^^ value used here after move
```
If the Views are indeed so cheap to copy (looks like they are) as claimed prior then they should be at the very least implement `Clone` if not outright `Copy`, but right now they don't as attempting to call `.clone()` on the entities in the `remove_coord_from_entity` causes:
```rust
error[E0599]: no method named `clone` found for struct `shipyard::view::EntitiesView<'_>` in the current scope
   --> src/game/mod.rs:235:15
    |
235 |                     entities.clone(),
    |                              ^^^^^ method not found in `shipyard::view::EntitiesView<'_>`
    | 
   ::: /home/overminddl1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/clone.rs:122:8
    |
122 |     fn clone(&self) -> Self;
    |        -----
    |        |
    |        the method is available for `std::sync::Arc<shipyard::view::EntitiesView<'_>>` here
    |        the method is available for `std::rc::Rc<shipyard::view::EntitiesView<'_>>` here
```
```rust

**Comment by leudz** [comment]
Ok, IDE issue when the compiler has no problem is super frustrating...
I'll rename the method and maybe it'll help. Which plugin are you using (just curious)?
I don't know if you're aware of `cargo check`, it should be fast.

I can make shared views clone you're right, I'll derive it.
They can't be `Copy` since the lock has to be incremented.
And `UniqueView` probably shouldn't derive it since it'll conflict with `T::clone`.
For your code I would personally make the functions take `&Entities`.

**Comment by OvermindDL1** [comment]
> Ok, IDE issue when the compiler has no problem is super frustrating...

Definitely the IDE bug though, which is the first one I've experienced so far so that's nice at least.

> Which plugin are you using (just curious)?

The plugin name is just `Rust`, for Clion (and intellij and others).  It does use `cargo check` (and clippy) to do such testing, which is why I'm curious why it pops that up.

> I can make shared views clone you're right, I'll derive it.

That will fix 95% of the issues I had with them in exchange for a little extra cost (incrementing a reference count when calling anything that consumes them does seem very needless when they could just take them by reference to begin with), last bit was just the `get` thing but honestly that's not really your fault (though overlapping function names, even if one is private, is likely to bite someone in the future, probably someone making a PR).

Better though would be to make things all calls (like `Get::get`) take them by reference overall though, so they don't consume them to begin with.  The fact they consume the calls is still irritating and needless incrementing a reference counter seems like wasted cost.  If it is really just so you don't have to pass a reference to a tuple of references then honestly I'd say just make them not able to take the base types like `View`/`ViewMut` at all and always force a reference to have to be used, even if that does pepper `(&blah,)get(...)` around as at least then it would be consistent.  Still though, if it took a reference, even if a reference to a tuple of references, then `(&blah, &blorp).get(...)` would still work, and it makes sense to pass a reference to such a tuple to child functions if reuse is to be done, so I still say things like `Get` should take `&self` instead of `self` anyway.

> They can't be `Copy` since the lock has to be incremented.

Ah interesting,

> For your code I would personally make the functions take &Entities.

That is what I do with child functions for the various storages.

**Comment by leudz** [comment]
I'm not sure how the plugins work. They can't "just" use `cargo check` output since they differ sometimes. Plus they have their own parsing and type solving algorithms,... AFAIK

You always have to use a reference when using `Get`. It doesn't consume the view and there is no incrementation.
It only consumes one or multiple references to storages, which is `Copy` (`&`) or not (`&mut`).
When you do:
```rust
let blah = coords.get(entity);
```
the compiler will actually do:
```rust
let blah = (&coords).get(entity);
```
It's used in the hierarchy recipe:
```rust
impl<'a, C> Iterator for AncestorIter<C>
where
    C: Get<Out = &'a Child> + Copy,
{
    type Item = EntityId;

    fn next(&mut self) -> Option<Self::Item> {
        self.get_child.get(self.cursor).ok().map(|child| {
            self.cursor = child.parent;
            child.parent
        })
    }
}
```
The bound `Get<Out = &'a Child> + Copy` makes it work with both `View` and `Window`.

I can't make `get` take a `&self` since you can do something like this:
```rust
(&view, &mut view_mut).get(entity);
```
This will get you a `(&T, &mut U)`, that would be impossible with `&self`.

**Comment by OvermindDL1** [comment]
> the compiler will actually do:

Yep I know, that's the auto-ref functionality, but consider this when you say:


> I can't make `get` take a `&self` since you can do something like this:
> 
> ```rust
> (&view, &mut view_mut).get(entity);
> ```
>
> This will get you a `(&T, &mut U)`, that would be impossible with `&self`.

Then auto-ref happens here as well is what I'm saying:

```rust
trait DoStuff {
    fn do_stuff(&self);
}

impl DoStuff for i32 {
    fn do_stuff(&self) { dbg!(self); }
}
impl DoStuff for (&i32, &str) {
    fn do_stuff(&self) { dbg!(self); }
}

fn main() {
    42i32.do_stuff();
    (&42i32, "hello").do_stuff();
}
```
Will print: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=61cdee030346f34193fb71c46f93f6df

And since it won't consume then in those rare cases that it could consume then it won't, and the code would work as expected.  Let me copy the `Get` into the playground and make the changes I'm thinking as I'm now doubting myself, so now `Get` is (ignore the `get` -> `get_by` change, I just don't want to conflict with Vec's `get` for this example but `get` works fine on own types):
```rust
pub trait Get<'a> {
	type Out: 'a;
	fn get_by(&'a self, entity: usize) -> Result<Self::Out, ()>;
}
```

And for this test let's just do a basic storage type for components, a dead simple no-one-would-really-use-because-holes `Vec<Option<_>>`, so let's implement it for a `Vec<Option<_>>`:
```rust
impl<'a, Comp: 'a> Get<'a> for Vec<Option<Comp>> {
	type Out = &'a Comp;
	fn get_by(&'a self, entity: usize) -> Result<Self::Out, ()> {
		if entity > self.len() {
			Err(())
		} else {
			match &self[entity] {
				Some(comp) => Ok(comp),
				None => Err(()),
			}
		}
	}
}
```
Repeat that for the other storage accessors as normal (so `View`/`ViewMut`/etc... in shipyard)/

And let's make a couple test components:
```rust
#[derive(Debug, PartialEq)]
pub struct A {
	name: String,
}

impl A {
	pub fn new(name: &str) -> A {
		A {
			name: name.to_owned(),
		}
	}
}

#[derive(Debug, PartialEq)]
pub struct B {
	team: i8,
}

impl B {
	pub fn new(team: i8) -> B {
		B { team }
	}
}
```

And let's make `main` and put a couple of 'storages' in it pre-populated:
```rust
	let acs = vec![Some(A::new("0")), Some(A::new("1")), None, Some(A::new("3"))];
	let bcs = vec![Some(B::new(0)), Some(B::new(1)), Some(B::new(2)), None];
```

And let's test this so far:
```rust
	assert_eq!( acs.get_by(1), Ok(&A::new("1")) );
	assert_eq!( bcs.get_by(1), Ok(&B::new(1)) );
```
So far this is the API you want, able to call `get` directly on the storage type (again, I renamed `get` to `get_by` here because Vec's already have a `get`, that would not be the case for your own types unless you are Deref'ing into something else that has a `get`).

Now what we are also wanting is this to work:
```rust
	assert_eq!((&acs,).get_by(1), Ok((&A::new("1"),)));
	assert_eq!((&acs, &bcs).get_by(1), Ok((&A::new("1"), &B::new(1))));
```

Where this has the aspects of both a non-reference tuple call and returns references, so first stab at trying to implement this:
```rust
impl<'a, C0: 'a + Get<'a>, C1: 'a + Get<'a>> Get<'a> for (&'a C0, &'a C1, ) {
    type Out = (C0::Out, C1::Out, );
    fn get_by(&self, entity: usize) -> Result<Self::Out, ()> {
        let _ = entity;
        match self.0.get_by(entity) {
            Ok(c) => {
                match self.1.get_by(entity) {
                    Ok(c) => {
                        Ok((c, c, ))
                    }
                    Err(err) => Err(err),
                }
            }
            Err(err) => Err(err),
        }
    }
}
```

And that works for the 2-tuple version, the 1-tuple is obvious, however I don't want to manually implement that for all supported tuple sizes, so a quick macro instead of that implementation:
```rust
macro_rules! implement_get_tuples {
	(GET, $self:ident, $entity:ident, ( $($ids:ident,)* ), ) => {
		Ok(($($ids,)*))
	};
	(GET, $self:ident, $entity:ident, ( $($ids:ident,)* ), $tid:ident : $pid:tt, $($rest_tids:ident : $rest_pids:tt,)*) => {
		match $self.$pid.get_by($entity) {
			Ok(c) => {
				implement_get_tuples!(GET, $self, $entity, ($($ids,)* c,), $($rest_tids: $rest_pids,)*)
			}
			Err(err) => Err(err),
		}
	};
	($($tids:ident : $pids:tt),*) => {
		impl<'a, $($tids: 'a + Get<'a>),*> Get<'a> for ($(&'a $tids,)*) {
			type Out = ($($tids::Out,)*);
			fn get_by(&self, entity: usize) -> Result<Self::Out, ()> {
				let _ = entity; // silence when unused
				implement_get_tuples!(GET, self, entity, (), $($tids: $pids,)*)
			}
		}
	};
}
```

And let's call it a few times with different tuple sizes:
```rust
implement_get_tuples!();
implement_get_tuples!(C0: 0);
implement_get_tuples!(C0: 0, C1: 1);
implement_get_tuples!(C0: 0, C1: 1, C2: 2);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4, C5: 5);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4, C5: 5, C6: 6);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4, C5: 5, C6: 6, C7: 7);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4, C5: 5, C6: 6, C7: 7, C8: 8);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4, C5: 5, C6: 6, C7: 7, C8: 8, C9: 9);
implement_get_tuples!(C0: 0, C1: 1, C2: 2, C3: 3, C4: 4, C5: 5, C6: 6, C7: 7, C8: 8, C9: 9, C10: 10);
```

That should be enough, and it all still works.

See the entire runnable code at:  https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c142d4f752dbef362b70a076756468ab

> This will get you a `(&T, &mut U)`, that would be impossible with `&self`.

So back to this, you say it is impossible with `&self` and yet it doesn't seem to be?  Or am I missing something else here?
