### ISSUE TITLE
`Workload::run_with_world()` panics when workload has a name

### ISSUE THREAD

**Issue by simast** [leudz/shipyard#132]
Noticed this on latest master. Pseudo code:

```rust
let (workload, _) = Workload::builder("Workload Name")
        .with_system(...)
        .build()?;

workload.run_with_world(&world)?;
```

Panics with:

> thread 'main' panicked at 'no entry found for key', <...>\shipyard-30604e9308997522\649db6f\src\scheduler\builder.rs:62:14

Note that if I use an empty string as a workload name `""` it works (seems like tests are using an empty string and therefore are passing).

**Comment by leudz** [comment]
Thanks for the report!
With multiple systems, the name was [`mem::take`](https://doc.rust-lang.org/std/mem/fn.take.html) before the last assignment so it was always an empty string.
