### ISSUE TITLE
A few questions for the user guide

### ISSUE THREAD

**Issue by davimiku** [leudz/shipyard#133]
Hello! Very nice crate here. I'm a beginner to ECS and somewhat of a beginner to Rust, and I've been experimenting with some of the different ECS crates. Yours in particular had a really nice recipe on Hierarchy that helped me with some of the things I want to experiment with.

I've been following along the user guide with the latest version available on crates.io (0.5.0 at the time of this comment), and I got a little stuck or had questions on a few parts.

1.
The [Add Entity page](https://leudz.github.io/shipyard/guide/master/fundamentals/add-entity.html) uses some examples of `U32` and `USIZE`. As a newcomer, I wasn't sure if those were types or where they came from, so it confused me for a bit. Eventually I realized they were just meant to be trivial examples of a Rust struct that can be a component. Maybe a quick note on the "Fundamentals" page with the definition of those structs and saying they'll be used throughout the examples.

2. The code examples on the [Delete Component page](https://leudz.github.io/shipyard/guide/master/fundamentals/delete-components.html) are currently broken, it's showing something like:

```
{{#include ../../../../tests/book/delete_components.rs:world}}
```

3. I was a little confused on the code example on the [non-Send and non-Sync page](https://leudz.github.io/shipyard/guide/master/going-further/non-send-sync.html), it's defining structs and implementing a `Component` trait. I wasn't able to find that trait on the [crates.io page](https://docs.rs/shipyard/0.5.0/shipyard/index.html), is that something that maybe used to exist but now doesn't and the user guide just needs to be updated?

4. Following along the Hierarchy recipe, one correction I think:

```
    if let Ok(p) = parents.get(parent) {
        // increase the parent's children counter
        p.num_children += 1;
```

I needed to change it to `if let Ok(mut p)` to mutate the `num_children`.

All in all, very nice! I think the only thing I'm currently still confused on is the `Component` trait, maybe the user guide is getting built from a branch other than the latest release?

**Comment by leudz** [comment]
Hi :raising_hand_man:

You are correct that the guide you linked isn't the one built for 0.5. There are 2 guides currently: [master](https://leudz.github.io/shipyard/guide/master) and [0.5](https://leudz.github.io/shipyard/guide/0.5.0).
All links you posted come from `master`, it's a WIP guide that is more or less up-to-date with the very latest changes on the repo.
As you noticed there are a few changes compared to 0.5, the biggest one being the new `Component` trait.
If you are using the 0.5 version you should definitely switch to the [0.5 guide](https://leudz.github.io/shipyard/guide/0.5.0).

Regarding the different issues you had, they do apply to `master`'s guide:

1. I 100% agree it should be mentioned somewhere.
Polishing the guide is the main thing I have to do to publish 0.6. During this polishing I'll remove `U32` and `USIZE` from everywhere and replace them with something like `Position` or `Health`.
2. Thanks for reporting it! I didn't know it was broken.
`delete` was removed a few months ago but added back, it seems the file containing the code referenced by the guide was not restored.
3. The `Component` trait is new, it has pros and cons but in the long run seems to be a good idea.
4. This is one of the nice thing about `Component`. In 0.5 when you access a component mutably you get a `Mut<T>`, a struct that keeps tracking information up-to-date. And that even if you are not actually tracking anything.
With 0.6, the `Component` trait allows storages that are not tracking mutation to return `&mut T`. This allows you to omit `mut` on most binding but also destructure the component directly.
