### ISSUE TITLE
AddComponent Send and Sync

### ISSUE THREAD

**Issue by mmulli** [leudz/shipyard#141]
Hi, I'm using 0.5.0 and trying to use this crate without any Send and Sync. I turned off default features and added the 'std' and 'thread_local' features but unfortunately came unstuck when I needed to add an entity with components that were not send and sync. The send and sync requirements in this case come from the crate's add_component.rs file.

I'd just like to know if Send and Sync is still on in relation to add_component for a reason or is this just something that still needs to be conditionally adjusted depending on feature flags?

And great work on the crate so far

**Comment by leudz** [comment]
Hi :raising_hand_man: 
I think I see the issue, is the compiler error something like:

> the trait bound `&mut shipyard::NonSendSync<shipyard::ViewMut<'_, Foo>>: shipyard::AddComponent` is not satisfied

I haven't implemented `AddComponent` directly for `!Send`/`!Sync` wrapper so you have to dereference it.

```rs
entities.add_component(entity, &mut *foo, Foo(std::rc::Rc::new(0)));
// instead of
entities.add_component(entity, &mut foo, Foo(std::rc::Rc::new(0)));
```
It's the same for `add_entity`.

I won't fix it for 0.5 but I'll fix it for master, thanks for reporting it :+1:

**Comment by leudz** [comment]
I hesitated to talk about this in my first reply and decided against it since you mentioned `add_component.rs`.
`World::add_entity` is a shorter version of `Entities::add_entity` but it only works for `Send + Sync` types. I'll make explicit in the function's doc.

With specialization I'll be able to make it work for `!Send`/`!Sync` types but we'll have to wait 😅

**Comment by mmulli** [comment]
Oh okay, are you implying above that ```Entities::add_entity``` does not require Send + Sync? Assuming this, I just made a simple test to see if that fixed my problem stemming from the use of RefCell but it seems that Sync is still required. Here is the full test:

```rust

use std::cell::RefCell;
use shipyard::{ViewMut, World, Component, track, EntitiesViewMut};

pub struct Speed(f32);

impl Component for Speed {
    type Tracking = track::Untracked;
}

pub struct SpeedWithRefCell(RefCell<f32>);
impl Component for SpeedWithRefCell {
    type Tracking = track::Untracked;
}

fn main() {

    let world = World::new();

    // Works fine when no RefCell is involved
    {
        let (mut entities, mut speeds) = world
            .borrow::<(EntitiesViewMut, ViewMut<Speed>)>()
            .unwrap();

        let _entity = entities.add_entity(&mut speeds, Speed(0.0));
    }

    // Compiler error when type involving RefCell is used
    {
        let (mut entities, mut speeds) = world
            .borrow::<(EntitiesViewMut, ViewMut<SpeedWithRefCell>)>()
            .unwrap();

        let _entity = entities.add_entity(&mut speeds, SpeedWithRefCell(RefCell::new(0.0)));
    }

}
```

The error is:
```rust
error[E0277]: `RefCell<f32>` cannot be shared between threads safely
  --> src/main.rs:37:14
   |
37 |             .borrow::<(EntitiesViewMut, ViewMut<SpeedWithRefCell>)>()
   |              ^^^^^^ `RefCell<f32>` cannot be shared between threads safely
   |
   = help: within `SpeedWithRefCell`, the trait `Sync` is not implemented for `RefCell<f32>`
note: required because it appears within the type `SpeedWithRefCell`
  --> src/main.rs:17:12
   |
17 | pub struct SpeedWithRefCell(RefCell<f32>);
   |            ^^^^^^^^^^^^^^^^
   = note: required because of the requirements on the impl of `IntoBorrow` for `ViewMut<'_, SpeedWithRefCell, Untracked>`
```
So it seems that this time the error is caused by SharedBorrow and ExclusiveBorrow which use atomics.

In my real use case I need to use RefCell for some special cases (Possibly miss guided :P) related to Safari and WASM. I could use Parking lot's RwLock type which works with nightly rusts wasm + atomics, though Safari's WASM runtime may not support that (Not sure). Anyway, my exact use case is a bit unusual so I won't side track you with too many details.

I guess my simple goal is just to work out a way to have shipyard accept components that may have a RefCell inside. No problem if this is not really feasible yet / a priority. I should be able to find a possibly uggly workaround on my own fork for the time being.

**Comment by leudz** [comment]
I guess I should've asked earlier for some code.
You just have to indicate your type is `!Send`/`!Sync` when you borrow.
In that case `NonSendSync<ViewMut<SpeedWithRefCell>>`. You might want to make a type alias for it.
And then you have to deref `speeds` when you add the entity.

```rs
use shipyard::{track, Component, EntitiesViewMut, NonSendSync, ViewMut, World};
use std::cell::RefCell;

pub struct Speed(f32);

impl Component for Speed {
    type Tracking = track::Untracked;
}

pub struct SpeedWithRefCell(RefCell<f32>);
impl Component for SpeedWithRefCell {
    type Tracking = track::Untracked;
}

fn main() {
    let world = World::new();

    {
        let (mut entities, mut speeds) =
            world.borrow::<(EntitiesViewMut, ViewMut<Speed>)>().unwrap();

        let _entity = entities.add_entity(&mut speeds, Speed(0.0));
    }

    {
        let (mut entities, mut speeds) = world
            .borrow::<(EntitiesViewMut, NonSendSync<ViewMut<SpeedWithRefCell>>)>()
            .unwrap();

        let _entity = entities.add_entity(&mut *speeds, SpeedWithRefCell(RefCell::new(0.0)));
    }
}

```

**Comment by mmulli** [comment]
Oh right. Thats clear now! My apologies for dragging you down that rabbit hole. Ill be sure to start with a 
Sample next time! Thanks for your help.

**Comment by leudz** [comment]
Great to hear it's working now, happy to help :smile:
