### ISSUE TITLE
Question about next release date

### ISSUE THREAD

**Issue by notinmybackyaard** [leudz/shipyard#146]
Would you please tell me when do you plan to release 0.6.0 version??
I really needs "tracing" feature... :)

**Comment by leudz** [comment]
It's hard to give a date but it's getting close.
I'm happy about the state of the code, I have to update the workload chapter, fix the [bunny_demo](https://leudz.github.io/shipyard/bunny_demo) (almost done) and write the release post.

In the meantime I released [alpha versions](https://crates.io/crates/shipyard/versions) where the `tracing` feature is available.

**Comment by notinmybackyaard** [comment]
Ok I'll try alpha version.
I really love your crate and thank you for your hard work!
