### ISSUE TITLE
Tracking information doesn't get reset after system runs

### ISSUE THREAD

**Issue by daigennki** [leudz/shipyard#147]
In my game engine, I've been trying out the tracking feature in a system like this, which runs every frame:
```rs
fn do_stuff_every_frame(mut components: ViewMut<MyComponent>)
{
	for c in components.inserted_mut().iter() {
		c.do_something_on_insertion();
	}	
	components.clear_all_inserted();
}
```
[The guide says:](https://leudz.github.io/shipyard/guide/0.6/going-further/tracking.html#reset)

> Inside workloads tracking information doesn't need to be reset. You will always get the operations that happened since the last run of the system.

And yet, I need the `clear_all_inserted` because without it, even though no `MyComponent` has been added to any entity since initial setup, the `for` loop runs every frame for all of the `components`. Is this correct behavior? Do I misunderstand what the guide says?

**Comment by leudz** [comment]
You shouldn't need to clear in workloads. Could you share how you are creating and running the workload?
I tried to reproduce your problem but it only ran once:

```rust
#[derive(Component)]
#[track(Insertion)]
struct MyComponent {}

fn do_stuff_every_frame(mut components: ViewMut<MyComponent>) {
    for _ in components.inserted_mut().iter() {
        dbg!("run");
    }
}
fn my_workload() -> Workload {
    do_stuff_every_frame.into_workload()
}

let mut world = World::new();

world.add_entity(MyComponent {});

world.add_workload(my_workload);

world.run_workload(my_workload).unwrap();
world.run_workload(my_workload).unwrap();
world.run_workload(my_workload).unwrap();
world.run_workload(my_workload).unwrap();
world.run_workload(my_workload).unwrap();
```

Output:

```txt
[tests\workload\mod.rs:169] "run" = "run"
```

**Comment by daigennki** [comment]
Oh, I was just running the system using `World::run` every frame, like this:

```rs
world.run_with_data(do_stuff_every_frame, some_data);
```
(it's actually a function that takes some data, hence the `run_with_data`)

Does it need to be in a workload?

**Comment by daigennki** [comment]
Read the guide again and

> Inside **workloads** tracking information doesn't need to be reset.

Whoops. There's my answer. Sorry about that!

**Comment by leudz** [comment]
No problem.
Workloads store when the last run was, `run` and `run_with_data` don't store anything that's why you need to clear manually.
