### ISSUE TITLE
Trouble with Get trait

### ISSUE THREAD

**Issue by notinmybackyaard** [leudz/shipyard#148]
Hi! First of all, I'd like to say thank you for this great work.
I'm trying to write my code with this and really enjoy it.
But I have minor problem now..
I wrote a generic function which is using .get() inside.
```
fn foo<T>(
    mut components: ViewMut<T>,
)
    where T: Component
{
  (&mut components)
      .get(id)
      .map(|mut component| { // compile error occurs because of immutable borrow
          // do something
      })
      .unwrap_or_default();
}
```
Here's problem..
Trait Get has various implements of get() function depending on component's tracking type
If i do not specify the tracking type, I can call immutable reference out type only.
I tried a lot to maintain generic way, but only succession was duplicate function with different trait bounding like below..
```
fn foo1<T>(
    mut components: ViewMut<T>,
)
    where T: Component<Tracking = Untracked>
}
fn foo2<T>(
    mut components: ViewMut<T>,
)
    where T: Component<Tracking = Modification>
}
```
Would you tell me if you know the answer?

**Comment by leudz** [comment]
Hi, thanks for the kind words =)

`Get` will very likely change in the future to make this easier.
For now you can add a bound to tell the compiler that there is an implementation for `&mut ViewMut`.

```rust
fn foo<'a, T>(mut components: ViewMut<'a, T>)
where
    T: Component + Default,
    for<'b> &'b mut ViewMut<'a, T>: Get,
{
    (&mut components)
        .get(id)
        .map(|mut component| {
            // do something
        })
        .unwrap_or_default();
}
```

**Comment by notinmybackyaard** [comment]
Thanks a lot! It works :)
I'm sorry but I encounterd additional problems.
First was when I bound my custom trait to generic T type, error occurs with this message:

> no method named `custom_trait_foo` found for associated type `<&mut ViewMut<'a, T> as Get>::Out` in the current scope

The code looks like below:
```
fn foo<'a, T>(mut components: ViewMut<'a, T>)
where
    T: Component + Default + CustomTrait,
        for<'b> &'b mut ViewMut<'a, T>: Get,
{
    (&mut components)
          .get(id)
          .map(|mut component| {
              component.custom_trait_foo(); // compile error
        })
        .unwrap_or_default();
}
```
I think that compiler doesn't know Out type is same as T
So I tried to add my custom trait bound to Out type but it doesn't work...

Second problem was occured when I registered this system function to nested workload.
```
fn main_loop() -> Workload {
    (
        foo::<Component>,
    ).into_workload()
}
```
When I comment out where cause in the system function, it works without error.

```
fn foo<'a, T>(mut components: ViewMut<'a, T>)
where
    T: Component + Default,
    //for<'b> &'b mut ViewMut<'a, T>: Get,
{
    (&mut components)
        .get(id)
        .map(|mut component| {

        })
        .unwrap_or_default();
}
```

And error message was like this:

> error[E0599]: the method `into_workload` exists for tuple `(for<'r, 's, 't0, 't1> fn(ViewMut<'_, A>, View<'r, B>, View<'s, C>, View<'t0, D>, UniqueView<'t1, E>) {foo::<'_, A>},)`, but its trait bounds were not satisfied

I'm afraid that I bother you so much, but it will be so helpful if you check these out for me...
Thank you!!

**Comment by leudz** [comment]
My solution wasn't "generic" enough 😅 Sorry.

For the first problem, adding a `DerefMut<Target = T>` bound will keep the system generic over trackings.
The second one was pretty bad, I was only able to find a solution because I've run into so many generics + lifetimes issues. Hopefully switching to GAT will make the compiler more accepting.

Here's the fully thing:
```rust

fn foo<T>(mut components: ViewMut<'_, T>)
where
    T: Component + Default + CustomTrait,
    for<'a, 'b> &'a mut ViewMut<'b, T>: Get,
    for<'a, 'b> <&'a mut ViewMut<'b, T> as Get>::Out: DerefMut<Target = T>,
{
    (&mut components)
        .get(id)
        .map(|mut component| {
            component.custom_trait_foo();
        })
        .unwrap_or_default();
}
```

**Comment by notinmybackyaard** [comment]
First solution makes everything perfect, even second problem! 🥰
Since I'm newbie to rust, I struggled with this issue so far..
Due to your reply, I made my code much more prettier.
I deeply appreciate to you not only this time, but also your work for shipyard 🙏
