### ISSUE TITLE
Is EntityId deleted if component is cleared?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#149]
```
let id = world.add_entity(SomeComponent());

fn clear(mut s: ViewMut<SomeComponent>) { s.clear(); }
```

Suppose there's a entity which has just one component. If I clear that component, entityId is also deleted?
and Is there any way to check if entityId exists without using component's get?

**Comment by leudz** [comment]
No the `EntityId` will still exist, without component.
You can check by borrowing [`EntitiesView(Mut)`](https://docs.rs/shipyard/latest/shipyard/struct.EntitiesView.html) and calliing [`is_alive`](https://docs.rs/shipyard/latest/shipyard/struct.EntitiesView.html#method.is_alive).
