### ISSUE TITLE
Is there any way to use Vec<ViewMut> as a parameter for a system?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#150]
I have some multiple components which are just for marker.
So they don't have any field.

For example,
```
#[derive(Component)] 
Apple();

#[derive(Component)] 
Banana();

#[derive(Component)] 
Grape();

...
```

The shipyard's system limits the number of parameter.
So I want to make a parameter as a vector.
Like this.
```
fn my_system(v: Vec<Box<Component>> // maybe this kind of thing?
{
    v.iter().for_each(|component| {
         // some condition
         component.add_component_unchecked(..);
         // do something
        }

}
```

Is there any way to do this kind of thing?

**Comment by leudz** [comment]
There are a few ways to solve your problem but a `Vec<Box<Component>>` isn't one of them because shipyard doesn't provide any interesting method on `Box<dyn Storage>`.

The easiest way to borrow more than 10 storages is to use tuples. Each argument of a system can be a tuple of up to 10 storages. And each of these can also be a tuple. So in theory you can borrow an infinity of storages.

```rust
fn system(
    (a, b, c, d, e, f, g, h, i, j): (
        View<A>,
        View<B>,
        View<C>,
        View<D>,
        View<E>,
        View<F>,
        View<G>,
        View<H>,
        View<I>,
        View<J>,
    ),
    (k, l): (View<K>, View<L>),
    m: View<M>,
) {}
```

Another way is to use custom views. Instead of directly borrowing storages, you create a struct to do the borrowing.
We derive 3 traits: `Borrow` allows borrowing from `World`, `AllStoragesBorrow` allows borrowing from `AllStorages` and `BorrowInfo` provide information for workloads.

```rust
#[derive(Borrow, AllStoragesBorrow, BorrowInfo)]
struct MyCustomView<'v> {
    a: View<'v, A>,
    b: View<'v, B>,
    c: View<'v, C>,
    d: View<'v, D>,
    e: View<'v, E>,
    f: View<'v, F>,
    g: View<'v, G>,
    h: View<'v, H>,
    i: View<'v, I>,
    j: View<'v, J>,
}
```

Of course you can use both methods at the same time and pick the one that makes the most sense.

**Comment by PudgeKim** [comment]
Thank you I didn't know shipyard's system can take tuple as a parameter. But.. there's still no way to get some parameter which is iterative?

**Comment by leudz** [comment]
It's technically possible but you'll have to write some boilerplate code.
This is for `add_component` for example:

```rust

fn system(mut all_storages: AllStoragesViewMut) {
    let dyn_components =
        all_storages.run(|mut dyn_component_list: UniqueViewMut<DynComponentList>| {
            std::mem::take(&mut dyn_component_list.0)
        });

    for dyn_component in dyn_components {
        dyn_add_component(dyn_component, &mut all_storages, EntityId::dead());
    }
}

#[derive(Unique)]
struct DynComponentList(Vec<Box<dyn DynComponent>>);

#[derive(Component)]
struct A;
#[derive(Component)]
struct B;

trait DynComponent: 'static + Send + Sync {
    fn add_component(self: Box<Self>, all_storages: &mut AllStorages, entity: EntityId);
}

impl<T: TupleAddComponent + 'static + Send + Sync> DynComponent for T {
    fn add_component(self: Box<Self>, all_storages: &mut AllStorages, entity: EntityId) {
        all_storages.add_component(entity, *self);
    }
}

fn dyn_add_component(
    component: Box<dyn DynComponent>,
    all_storages: &mut AllStorages,
    entity: EntityId,
) {
    component.add_component(all_storages, entity);
}
```

**Comment by PudgeKim** [comment]
It's a bit complicated but anyway thank you very much for your kind answer.

**Comment by PudgeKim** [comment]
Hello! I have one more question after I saw your answer again.
Your example uses `AllStoragesViewMut` in the system. So it means the system can't be run in parallel with other system. (Is it right?)

Is there anyway to use `Unique` which contains vector of components as a system's parameter?

What I want to do is like
```
#[derive(Unique)]
struct MyUnique {
    field1: Vec<Box<dyn DynComponent>>,
    field2: Vec<Box<dyn DynComponent>>,
}

fn system1(my_unique: UniqueViewMut<MyUnique>) {
    ...

    my_unique.field1.iter().for_each(|component| {
        dyn_add_component(...);
    }

    ...
}
```

**Comment by PudgeKim** [comment]
Hello! I have one more question!

```
#[derive(Unique)]
struct MyUnique {
    field1: Vec<ViewMut<>>,
    field2: Vec<ViewMut<>>,
}

impl MyUnique {
    fn add_component(&self, entity_id: EntityId, something: ..) {
        let index = get_index(something);
        if some_condition {
            self.field1[index].add_component_unchecked(entity_id, SomeComponent());
        }
    }
}

fn my_system(
    my_unique: UniqueView<MyUnique>,
    some_component: ViewMut<SomeComponent>, // I don't want to add this as a system's parameter because MyUnique contains it in vec.
)
{
    ..
    my_unique.add_component(..);
    ..
}
```

Is this technically possible?

**Comment by leudz** [comment]
Hey!
I don't understand what you're trying to do in this example.
In your first post you had multiple components and were trying to borrow them using a `Vec`. While not possible I understood the idea behind it.

Could you explain more what you're trying to do?

**Comment by PudgeKim** [comment]
In your second answer, you used `AllStoragesViewMut`. It means the system can't run in parallel with other systems.
So I want to use UniqueView/UniqueViewMut which contains Vector as a system's parameter.
But reading your answer again, it seems it's impossible to add components without using `AllStoragesViewMut`.

**Comment by leudz** [comment]
It's possible but the code is unusual.
All the logic happens inside a custom view. They can borrow things more freely than built-in views. But you have to tell shipyard what they borrow.

```rust
fn main() {
    let world = World::new();

    world.add_unique(DynComponentList(vec![Box::new(A), Box::new(B)]));

    world.run(add_dyn_component_list);
}

// All the logic happens in the `Borrow` implementation
fn add_dyn_component_list(_: AddDynComponents) {}

#[derive(Unique)]
struct DynComponentList(Vec<Box<dyn DynComponent + Send + Sync>>);

trait DynComponent {
    fn add_component(
        self: Box<Self>,
        entity: EntityId,
        // This could be `&AllStorages`, it depends if you want to use this inside another system or not
        // You can get `&AllStorages` by calling `world.all_storages()` in `AddDynComponents::borrow`
        world: &World,
        last_run: Option<u32>,
        current: u32,
    ) -> Result<(), shipyard::error::GetStorage>;
}

impl<T: Component + Send + Sync> DynComponent for T {
    fn add_component(
        self: Box<Self>,
        entity: EntityId,
        world: &World,
        last_run: Option<u32>,
        current: u32,
    ) -> Result<(), shipyard::error::GetStorage> {
        let mut view: ViewMut<T> =
            <ViewMut<T> as IntoBorrow>::Borrow::borrow(world, last_run, current)?;

        view.add_component_unchecked(entity, *self);

        Ok(())
    }
}

struct AddDynComponents(());

impl IntoBorrow for AddDynComponents {
    type Borrow = AddDynComponents;
}

impl<'a> Borrow<'a> for AddDynComponents {
    type View = AddDynComponents;

    fn borrow(
        world: &'a World,
        last_run: Option<u32>,
        current: u32,
    ) -> Result<Self::View, shipyard::error::GetStorage> {
        let mut dyn_components = <UniqueViewMut<DynComponentList> as IntoBorrow>::Borrow::borrow(
            world, last_run, current,
        )?;

        for dyn_component in &mut dyn_components.0.drain(..) {
            dyn_component.add_component(
                EntityId::new_from_index_and_gen(0, 0),
                world,
                last_run,
                current,
            )?;
        }

        Ok(AddDynComponents(()))
    }
}

unsafe impl BorrowInfo for AddDynComponents {
    fn borrow_info(info: &mut Vec<shipyard::info::TypeInfo>) {
        // This must be a full list of all possible components that can be in `DynComponentList`
        ViewMut::<A>::borrow_info(info);
        ViewMut::<B>::borrow_info(info);
    }
}
```

For workloads there are 2 paths, either you know in advance the full list of components that might go in `DynComponentList` or you do not know.

1. If you know you can use the implementation of `BorrowInfo` for `AddDynComponents` above and it'll will work perfectly fine
2. If you don't know then it's more complicated.
Workloads build their ordering at creation so you can't reuse or store any workload that use `AddDynComponents`. In addition there is no way for `AddDynComponents`'s implementation of `BorrowInfo` to get an accurate list. What you could do is create the list of `TypeId`s and then add it as labels to the system, basically do the job of `BorrowInfo` manually. I can provide a snippet but hopefully you are in the first scenario.
