### ISSUE TITLE
Circumventing borrow restrictions across language boundaries

### ISSUE THREAD

**Issue by j-martina** [leudz/shipyard#154]
I'm adding Lua into a game I'm working on for faster prototyping, and trying to replicate a pattern I've seen in multiple other (C++) game engines.

- Iterate over a group of components mutably, changing state Rust-side.
- If a state change meets a condition, invoke a Lua callback.
- The callback manipulates state on the entity whose state was just changed, or any other entity in the world.

Allowing Lua closures such broad access is necessary (in case something is desired like the player characters affecting the other entities around them upon taking damage or some such), but if, for example, `ViewMut<Health>` is borrowed in the outer loop, a Lua closure can't borrow `ViewMut<Health>` again.

I no longer think of this as being a Lua problem, since this pattern would work fine if doing something naive like iterating over a `Vec` where every "entity" was one object. I've concluded that what I'm looking for is a way to iterate over a `Storage` without taking out a borrow.

That said, no other ECS crate I've seen has a way to do this, so I expect it's either out of scope, unfeasible, or wouldn't have a nice API, or wouldn't be performant (although I don't want to assume either way). If I'm right, and I just to need to change direction entirely, say so and I'll close this immediately.

Thanks in advance.

**Comment by leudz** [comment]
Hi! You can do basically the same as with `Vec<T>`. First modify the data and collect the indices of the ones modified. Then iterate the indices and call lua.

Most Rust ECS have a way to track component modification so you can separate a bit the component modification and ids collection.

Here's an example based on your description:
```rust
use mlua::{Function, Lua, UserData};
use shipyard::{Component, EntitiesViewMut, EntityId, IntoIter, IntoWithId, View, ViewMut, World};
use std::sync::Arc;

#[derive(Component)]
#[track(Modification)]
struct Health(u32);

#[derive(Clone)]
struct MyId(EntityId);

impl UserData for MyId {
    fn add_fields<'lua, F: mlua::UserDataFields<'lua, Self>>(fields: &mut F) {
        fields.add_field_method_get("get", |_, this| Ok(this.0.inner()));
    }
}

fn main() {
    let world = Arc::new(World::new());

    let lua = Lua::new();
    let world_clone = world.clone();
    let mutating_lua_func = lua
        .create_function(move |_, eid: MyId| -> Result<(), mlua::Error> {
            let world = world_clone.clone();

            // do whatever with world
            println!("Health is 0 for {:?}", eid.0);

            Ok(())
        })
        .unwrap();
    lua.globals()
        .set("mutating_func", mutating_lua_func)
        .unwrap();

    world.run(
        |mut entities: EntitiesViewMut, mut vm_health: ViewMut<Health>| {
            entities.add_entity(&mut vm_health, Health(1));
        },
    );

    world.run(modify_health_rust);
    modify_health_lua(&lua, &world);
}

fn modify_health_rust(mut vm_health: ViewMut<Health>) {
    for mut health in (&mut vm_health).iter() {
        health.0 -= 1;
    }
}

fn modify_health_lua(lua: &Lua, world: &World) {
    let entities: Vec<EntityId> = world.run(|v_health: View<Health>| {
        v_health
            .modified()
            .iter()
            .with_id()
            .filter_map(|(eid, health)| (health.0 == 0).then(|| eid))
            .collect()
    });

    let mutating_lua_func: Function = lua.globals().get("mutating_func").unwrap();
    for eid in entities {
        mutating_lua_func.call::<_, ()>(MyId(eid)).unwrap();
    }
}
```

This is only an example, I don't know how well it would run.
Repeatedly calling Lua might be a bad idea and borrowing storages repeatedly definitely has a cost.

Putting the `World` inside an `Arc` is not very problematic. All methods on `World` that require an exclusive reference are only shortcuts to the same methods with views.
You can do some setup before putting the `World` inside the `Arc` too.

**Comment by j-martina** [comment]
I can see how the performance may be affected, but I can definitely use it at small scales. Thank you.

Although on another project, the specification would demand that Lua calls (able to mutate) be interleaved with Rust mutation, per entity, like this:

```rust
for mut health in (&mut vm_health).iter() {
    health.0 -= 1;

    if health.0 <= 1 {
        let mutating_lua_func: Function = lua.globals().get("mutating_func").unwrap();
        mutating_lua_func.call::<_, ()>(lua_entity_repr).unwrap();
    } else {
        health.0 += 1;
    }
}
```

where `lua_entity_repr` would be a table or a userdata tied to that same entity that a script could operate on to manipulate components.

This is impossible, right? It probably wouldn't be good anyway, since every function call would have to go through the `Arc` (and possibly unlock a mutex too) and then request access to a storage somehow, so a complex script would be very slow. I may still end up not using ECS for this kind of situation.

**Comment by leudz** [comment]
For interleaving access you can do it by trading even more speed. You can wrap each component in `RefCell`/`RwLock`.

Or you can go `unsafe` and then you don't have to pay a runtime penalty but you'd have to be careful.

**Comment by j-martina** [comment]
I ran some benchmarks and it looks like the extra indirection of a lock over the components would make it too slow. Unsafe is something I'm willing to tolerate, though.

I'll close this issue here, but if there's a "best" way to do achieve that (I doubt I can coerce `View` into `ViewMut` via `std::mem::transmute` without violating internal expectations?), I'd be happy to hear them.

All your help thus far is appreciated; I know this is a bit of a niche request.
