### ISSUE TITLE
How to iterate mutable component in parallel?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#161]
I can iterate single component in parallel if it is View type.
`let ParIter::Tight(par_iter) = (&my_views).par_iter() else { unreachable!() };`

Can I iterate ViewMut component in parallel?

What I wanna do is running the code below in parallel
```
some_components.inserted().iter().with_id().for_each(|(id, ..|) {
  (&mut my_mutable_views)
    .get(id)
    .map(|my_view| { 
        // modify component
       ...
  })
    .....
```

As you see, it's safe because mutable view is accessed by each id.
But I don't know how to iterate in parallel

**Comment by leudz** [comment]
`ParallelIterator` is not implemented for iterators that use `with_id`. See https://github.com/leudz/shipyard/issues/156
But if you are just using the id to get the component from the `ViewMut` then you can do:

```rust
(some_components.inserted(), &mut my_mutable_views)
    .par_iter()
    .for_each(|(_, _)| {
        // modify component
    });
```

----

> As you see, it's safe because mutable view is accessed by each id.

While true, the compiler doesn't know that so you'd get a compile error.

```rust
some_components.inserted().par_iter().for_each(|_| {
    (&mut my_mutable_views) // cannot borrow `my_mutable_views` as mutable, as it is a captured variable in a `Fn` closure
        .get(EntityId::dead())
        .map(|my_view| {
            // modify component
        });
});
```

**Comment by PudgeKim** [comment]
I didn't know I can use (inserted, &mut ..) + par_iter !
thank you.

**Comment by PudgeKim** [comment]
What if I need a EntityId with `(some_components.inserted(), &mut my_mutable_views)` ?
I saw the issue #156. 
There's no way to get a EntityId in `(some_components.inserted(), &mut my_mutable_views).par_iter()` ?

**Comment by leudz** [comment]
Currently I think the only way is to collect a non-parallel iterator into a `Vec` and then use a parallel iterator on it.

**Comment by PudgeKim** [comment]
I'm sorry to question again in this issue but I have some problem..
```
#[derive(Component)]
#[track(All)]
struct SomeComponent1 {
  owner_id: EntityId,
  ...
}

#[derive(Component)]
struct SomeComponent2 { .. }

some_comp1.inserted().iter().for_each(|(comp1)| {
  (&mut some_comp2)
    .get(comp1.owner_id)
    .map(|| { // some heavy work and need to write the result to SomeComponent2 })
   ...

```

SomeComponent1's entityId is different from SomeComponent2.
Is there anyway to run this system in parallel?

**Comment by PudgeKim** [comment]
I'm sorry to ask again in this issue but I have some problem..
What if `some_component`'s entityId is different from `my_mutable_view`?
Then I can't use `(some_components.inserted(), &mut my_mutable_views)`.

so code is like
```
some_components
  .inserted()
  .for_each(|some_comp| {
    let entity_id = some_comp.owner_id;
    (&mut my_mutable_views)
      .get(entity_id)
      .map(|my_view| {
           // modify my_view
      })
     ...
```

There's some reason that some_component has a different EntityId.
In this case, Is there anyway to run it in parallel..?

**Comment by leudz** [comment]
There is no clean way to do this, you'd have to collect in a  `Vec` first.

Many concurrent `HashMap` use locks under the hood, that could work in theory, no idea how well it would work though.

**Comment by PudgeKim** [comment]
Happy New Year!
Could you tell me how to do NO clean way?
I think it would help my Rust skills and also understand shipyard.

**Comment by leudz** [comment]
Happy new year! 🎉 

What I said in my previous answer was kind of wrong. Because you use different `EntityId` there is no way to `get` from the mutable view in parallel.
So I did the opposite:

```rust
let some_components = some_components
    .inserted()
    .iter()
    .map(|some_comp| (some_comp.owner_id, some_comp))
    .collect::<HashMap<_, _>>();

let my_mutable_views = (&mut my_mutable_views)
    .iter()
    .with_id()
    .map(|(id, my_view)| (some_components.get(&id).unwrap(), my_view))
    .collect::<Vec<_>>();

my_mutable_views
    .into_par_iter()
    .for_each(|(some_comp, my_view)| {
        // modify my_view
    });
```

This should work but it'll have a pretty steep starting cost. The `Vec` is only needed because `with_id` doesn't implement `ParallelIterator`.
Alternatively you could use a lock for all `my_view`, either directly in the storage or create a `Vec` in the system. Then you'll be able to `get` immutably and lock.

**Comment by PudgeKim** [comment]
Hello..! Is there any solution to make a vector that contain mutable reference? I'm stuck ..

let my_mutable_views = (&mut my_mutable_views)
    .iter()
    .with_id()
    .map(|(id, my_view)| (some_components.get(&id).unwrap(), my_view)) // I need to change this to (&mut comp).get()
    .collect::<Vec<_>>();

**Comment by leudz** [comment]
Hey! what error are you getting?

**Comment by PudgeKim** [comment]
`captured variable cannot escape `FnMut` closure body`
I understand the error but I don't know how to solve it

**Comment by PudgeKim** [comment]
now I tried the code below and it is compiled! 
But I still don't know how to make it par_iter and I wonder there's more clear/easier way to do this kind of thing.

```
trait CustomIterator{
    type Item<'a>
        where
            Self: 'a;

    fn next<'a>(&'a mut self) -> Self::Item<'a>;
}

struct BuffIterator<'a, 'b> {
    property_bags: ViewMut<'a, PropertyBag>,
    buffs: &'b HashMap<EntityId, Vec<(EntityId, i64)>>, // (buff_entity_id, Vec<Buff>)
    keys: Vec<EntityId>,
    idx: usize,
}

impl<'a, 'b> BuffIterator<'a, 'b> {
    pub(crate) fn new(
        property_bags: ViewMut<'a, PropertyBag>,
        buffs: &'b HashMap<EntityId, Vec<(EntityId, i64)>>,
    ) -> Self {
        let keys = buffs.keys().map(|e| *e).collect();
        Self {
            property_bags,
            buffs,
            keys,
            idx: 0
        }
    }
}

impl<'x, 'y> CustomIterator for BuffIterator<'x, 'y> {
    type Item<'a> = Option<(&'a mut PropertyBag, Vec<(EntityId, i64)>)> where Self: 'a;

    fn next<'a>(&'a mut self) -> Self::Item<'a> {
        if self.idx >= self.keys.len() {
            return None;
        }

        let owner_entity_id = self.keys[self.idx];
        let info = self.buffs.get(&owner_entity_id).unwrap().clone();
        let p = (&mut self.property_bags).get(owner_entity_id).unwrap();
        self.idx += 1;

        Some((p, info))
    }
}
```

**Comment by leudz** [comment]
Yes what you had working (`CustomIterator`) was a streaming iterator. The difference with the `Iterator` trait in std is that you can only have one element at a time so `collect` for example can't be implemented. Another thing is it can't be made parallel since you need multiple elements.

It could work with `unsafe` (and that's what `iter`/`par_iter` do) but not enough of `SparseSet`'s internal fields are exposed.
`index_of` can give you the index of components but there is only `as_slice` and you'd need `as_mut_slice` or maybe `data_mut_ptr`.

I can do that in the next few days.

**Comment by PudgeKim** [comment]
oh I didn't know you answered to my last post which I deleted. anyway I understand and thank you!
I think it would be nice if `as_slice_mut` method is added in the future.
