### ISSUE TITLE
What is benefit of splitted workloads?

### ISSUE THREAD

**Issue by notinmybackyaard** [leudz/shipyard#164]
Hi! I have a question about how to organize my systems with workload.
what I understand about workload is, the more systems that are nested within a single workload, the better it will perform in parallel.
so now i'm using single workload named main loop.
but when I observe shipyard example projects, most of them using splitted workloads.
would you tell me what is benefit of splitted wokloads?

**Comment by leudz** [comment]
Hi!
> what I understand about workload is, the more systems that are nested within a single workload, the better it will perform in parallel.

Yes as long as you don't have borrow conflicts.

> would you tell me what is benefit of splitted wokloads?

I think the piece you are missing is that workloads are flattened when created.
So even if your "main" workload uses nested workloads that uses nested workloads,... when you add the "main" workload it will be a big list of systems, the nesting will have disappeared completely.

Here's an example:

```rust
fn main() {
    let world = World::new();

    world.add_workload(main_loop);

    dbg!(world);
}

fn main_loop() -> Workload {
    (workload1, workload1, workload1).into_workload()
}

fn workload1() -> Workload {
    (sys1, sys2, sys3).into_workload()
}

fn sys1() {}
fn sys2() {}
fn sys3() {}
```

We add 3 times the systems using 1 level of nesting. But the debug is:

```
World(
    AllStorages {
        storage_count: 1,
        storages: [
            shipyard::entities::Entities,
        ],
    },
    Scheduler {
        default_workload: Workload("main_loop"),
        workload_count: 1,
        workloads: [
            Workload("main_loop"),
        ],
        system_count: 3,
        systems: [
            "sys1",
            "sys2",
            "sys3",
        ],
    },
)
```

Only 1 workload, the 3 systems are also only present once and will be reused.

**Comment by notinmybackyaard** [comment]
Oh i got it :)
I appreciate for your kindness!
