### ISSUE TITLE
How to query a entity by a component value, not component type?

### ISSUE THREAD

**Issue by tempbottle** [leudz/shipyard#172]
How to query a entity's component Set by a component value, not component type? Is ECS, such as shipyard, can handle this with high performance?

Do this with Component Typed filter is work fine. But maybe with a poor performance.  Since the queried out Set may has large length.

As the example, `is_in_acid` is the value filter.

```
use shipyard::{Component, IntoIter, View, ViewMut, World};

#[derive(Component)]
struct Health(u32);
#[derive(Component)]
struct Position {
    x: f32,
    y: f32,
}

fn in_acid(positions: View<Position>, mut healths: ViewMut<Health>) {
    for (_, mut health) in (&positions, &mut healths)
        .iter()
        .filter(|(pos, _)| is_in_acid(pos))
    {
        health.0 -= 1;
    }
}

fn is_in_acid(pos: &Position) -> bool {
    // ======> filter here by positon value 
    pos.x > 100 && pos.y < 50 && pos.x <150 && pos.y > 0
}

fn main() {
    let mut world = World::new();

    world.add_entity((Position { x: 0.0, y: 0.0 }, Health(1000)));

    world.run(in_acid);
}
```

**Comment by leudz** [comment]
This is a broad question and there are a lot of answers based on each specific case.

`is_in_acid` for example could be handled using a spacial data-structure.
Or using only shipyard you could check only entities that moved and tag/untag them.
But most likely this isn't an issue to begin with. If you look [here](https://github.com/rust-gamedev/ecs_bench_suite) you'll see that iterating 2 storages with 10k entities takes 25us. This will vary based on the hardware but it's a tiny number.
The ECS is usually not the bottleneck.

For the general question "How to query a entity by a component value" you could use custom views to build and update an index like discussed [here for bevy](https://github.com/bevyengine/bevy/discussions/1205).
But it would be pretty complicated and I don't know what the actual performance would look like.
