### ISSUE TITLE
How to make certain systems always run first?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#176]
```
pub fn my_systems() -> Workload {
  first_system
    .before_all(ALL_SYSTEMS)
    .into_workload()
}
```

I want to do something like this.
I can do it `.before_all(all_workload_except_first_system)`.
but I just wonder if there's a more convenient way

**Comment by leudz** [comment]
You can do:

```rust
pub fn my_systems() -> Workload {
  Workload::new("")
    .with_system(first_system)
    .with_barrier()
    .with_system(...)
}
```

Under the hood it'll create a tag and use before/after.

Or something like this:

```rust
pub fn my_systems() -> Workload {
  (
    first_system,
    |_: AllStoragesViewMut| {},
    ...
  )
  .into_workload()
}
```

It'll make a useless borrow but that shouldn't be a problem.

**Comment by PudgeKim** [comment]
why this doesn't work? 
```
fn my_systems() -> Workload {
  (
    first_system,
   |_: AllStoragesViewMut| {},
  workload1().
  workload2(),
  ...
).into_workload()
}
```

workload1 and workload2 have multiple systems.
In this code, schedular doesn't gaurantee that `first_system` runs first.

**Comment by leudz** [comment]
🤔 I'm guessing some systems in `workload1` or `workload2` use `before_all`, I didn't think of that.
`with_barrier` won't have this issue or you'll have to use `before_all(all_workload_except_first_system)` I'm afraid.

**Comment by PudgeKim** [comment]
As you said, `workload1` and `workload2` use `before_all`. 
The problem of using `with_barrier` is 
```
Workload::new("")
    .with_system(first_system)
    .with_barrier()
    .with_system(...)
```

I should put system in this code. I want to put workload instead of system. I need something like `with_workload `.

So I tried below.
```
(
first_systems
  .before_all(workload1)
  .before_all(workload2),
workload1(),
workload2()
).into_workload()
```

But It also doesn't gaurantee that first_systems runs first.
Is it a bug?

**Comment by leudz** [comment]
`with_workload` is called `merge`, maybe it should change name, it's probably easier to find as `with_workload`.

> Is it a bug?

I would say more a limitation. When you call the function `workload1` it'll return a `Workload` that doesn't know about the function. So using the function as a tag doesn't work.

Without calling the function it should work.

```rust
(
  first_systems
    .before_all(workload1)
    .before_all(workload2),
  workload1,
  workload2,
).into_workload()
```

Technically you can also do `.into_workload().tag(workload1)` in the `workload1` function.

**Comment by PudgeKim** [comment]
thank you ~~! 
and I'm sorry but what version or what kind of trait should I import to use `with_barrier`?

**Comment by leudz** [comment]
It's only available on the master version. (I'll make a release soon-ish)
You don't need any trait, it's a direct method.

(I just added `with_workload` if you prefer this name)

**Comment by PudgeKim** [comment]
I think `with_workload` is better :)
thank you for answering!
