### ISSUE TITLE
Create a way to easily derive the Label trait

### ISSUE THREAD

**Issue by AribYadi** [leudz/shipyard#180]
The [`Label`](https://docs.rs/shipyard/latest/shipyard/trait.Label.html) trait have some required functions that are just bothersome to implement every time I need to create a custom label.
My idea is to create a derive macro that derives the [`Label`](https://docs.rs/shipyard/latest/shipyard/trait.Label.html) trait with an implementation like this private macro over [here](https://github.com/leudz/shipyard/blob/master/src/scheduler/label.rs#L24).
Another idea is just to `#[macro_export]` the previously mentioned macro.

**Comment by leudz** [comment]
I tested it a bit but don't hesitate to tell me if the macro doesn't work on some types.
