### ISSUE TITLE
Tracking compiles but panics on run

### ISSUE THREAD

**Issue by RicardRC** [leudz/shipyard#183]
Dummy function

```
fn update_positions_from_velocity(
	t: UniqueView<Tick>,
	mut positions: ViewMut<Position>,
	velocities: View<Velocity, track::InsertionAndModification>,
) {
	for (mut x, v) in (&mut positions, &velocities).iter() {
		x.0 += t.delta_time * v.0;
	}
	for _ in velocities.inserted_or_modified().iter() {}
}
```

when running, gives me the error
`
thread 'LocalUniverse:LocalUniverse' panicked at 'called 'Result::unwrap()' on an 'Err' value: System pixiel_core::core::local_universe::systems::simulation_systems::update_positions_from_velocity failed: Insertion and Modification tracking is not enabled for shipyard::sparse_set::SparseSet<pixiel_core::core::local_universe::components::Velocity> storage.', src\core\local_universe.rs:228:18
`

happens on 7d58021 and I don't know since when it happens, as I was just trying the tracking feature for the first time.
(Tried to add `#[track(InsertedOrModified)]` at the component, but that does not compile, with 
```
error: cannot find attribute `track` in this scope
   --> src\core\local_universe\components.rs:139:3
    |
139 | #[track(InsertedOrModified)]
    |   ^^^^^
    |
```
)

**Comment by leudz** [comment]
If you're not using a workload you need to manually enable tracking.
You can use `World::track_insertion` and `World::track_modification`.
There are similar methods on the view.

For the proc macro, the design has changed since 0.6. You don't declare it on the component anymore but you either manually enable it or let the workload do it when it's added to the `World .`

**Comment by RicardRC** [comment]
I'm using workloads, .into_workload() in particular, then executing with .run_with_world(&world).unwrap();

**Comment by leudz** [comment]
Oh I see.
🤔 So currently this method doesn't enable tracking, should it? I'm not sure.

There is `ScheduledWorkload::apply_tracking` that you can call to enable all trackings used by this workload.
You only have to call it once but calling it multiple times shouldn't cause any issue (if it does it's a bug on my side).

----

It would be easy to make `run_with_world` call `apply_tracking` but it would make it always borrow `AllStorages` which could be surprising.
I'll have to think about it.

**Comment by RicardRC** [comment]
I have multiple workloads, that I execute interleaved, but I have already prepared before execution, at initialization.
Would tracking a single component on two workloads make the tracked changes become available on both workloads, or one would consume the changes for the other? (Not that I want one or the other, just to know).

**Comment by RicardRC** [comment]
Okay, calling apply_tracking on the scheduled workload before calling run removes the execution crash :) And the sweet parallel execution is kept alive. Thank you very much! 
<img width="739" alt="image" src="https://github.com/leudz/shipyard/assets/35220750/dd4971aa-385a-4ff1-a6d0-a11dd271f3e8">
I'll proceed to test if two modification trackings on the same component on different read only views on different systems can be run in parallel and report what I expect... The library you made is a pleasure to use, and it always ends up able to do whatever aberration I try :)
