### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by ealmloff** [leudz/shipyard#185]
I may have encountered a memory in shipyard. If you add and remove entities repeatedly memory usage goes up.

Minimal reproducible example (leak happens in both debug and release mode, but it is much more noticeable in release mode):

```rust
use shipyard::{Component, EntityId, IntoIter, View, ViewMut, World};

#[derive(Component)]
struct Object {
    large_object: [u8; 1024],
}

fn main() {
    let mut world = World::new();
    let add_count = 10000;

    loop {
        let entities: Vec<_> = (0..add_count)
            .map(|_| {
                world.add_entity((Object {
                    large_object: [0; 1024],
                },))
            })
            .collect();

        for id in entities {
            world.delete_entity(id);
        }
    }
}
```

**Comment by leudz** [comment]
Which system are you using? Are how much memory are you seeing?

I tried your example on Windows and Linux but didn't see anything strange.
I let it run for a few minutes, it started at 10.4mb and ended at 11.1mb.
I think this increase can be explained by how `EntityId`s are recycled.
Each ECS picks the trade-offs they want. Shipyard guaranties that all IDs from a single `World` are unique.
To do that when the generation reaches its maximum, the slot for this entity becomes dead and a new one is used.

For your example that means every `u16::MAX` iterations, 10000 new entity slots are allocated.

**Comment by ealmloff** [comment]
I'm running the code on a `macos` system. That is similar to the amount of memory leaking that I was observing. That could be the issue I am running into here. If that is intended behavior, I will close this issue
