### ISSUE TITLE
Better error message for boxed traits in components

### ISSUE THREAD

**Issue by snyball** [leudz/shipyard#189]
Hi! I ran into a bit of confusion with the following code:

```rust
use std::fmt;

use shipyard::{Component, World};

pub trait Lmao: fmt::Debug {
    fn lmao(&self);
}

#[derive(Debug)]
pub struct Ayy;

impl Lmao for Ayy {
    fn lmao(&self) {
        println!("ayy lmao");
    }
}

#[derive(Debug, Component)]
pub struct Container {
    thing: Ayy,
    boks: Box<dyn Lmao>,
}

pub fn main() {
    let boks: Box<dyn Lmao> = Box::new(Ayy);
    let thing = Ayy;
    let mut world = World::new();
    world.add_entity((Container { boks,
                                  thing },));
}
```

It doesn't compile when the `boks` struct member is added, and the error message is a bit confusing.

Eventually I figured out that I needed to add `Send + Sync` trait bounds for the `Lmao` trait, and this is documented in [`!Send and !Sync Components`](https://leudz.github.io/shipyard/guide/master/going-further/non-send-sync.html?highlight=sync#send-and-sync-components). The `Component` derive macro doesn't have access to type information, but, maybe the derive-macro could conditionally add something like this if `thread_local` is not enabled:

```rust
mod __private {
    use super::Container;
    trait SyncSend: Send + Sync {}
    impl SyncSend for Container {}
}
```

Which would produce a much more helpful error message.

**Comment by leudz** [comment]
Hi, this is a good idea. I was a bit worried about feature flag resolution but it should be fine.
