### ISSUE TITLE
How to modify track deletion component?

### ISSUE THREAD

**Issue by SSSxCCC** [leudz/shipyard#196]
A track removal component can be modified in this way:

```rust
#[derive(Component)]
#[track(Removal)]
struct TrackRmovalComponent {
    a: i32,
}

fn modify_system(mut c: ViewMut<TrackRmovalComponent>) {
    for c in (&mut c).iter() {
        c.a = 0; // this works
    }
}
```

But a track deletion component can not be modified in this way:

```rust
#[derive(Component)]
#[track(Deletion)]
struct TrackDeletionComponent {
    a: i32,
}

fn modify_system(mut c: ViewMut<TrackDeletionComponent>) {
    for c in (&mut c).iter() {
        c.a = 0; // cannot assign to `c.a`, which is behind a `&` reference
    }
}
```

shipyard version: 0.6.2

So how to modify track deletion component?

**Comment by leudz** [comment]
Thanks, there was a missing impl for `track::Deletion`. I've added it in https://github.com/leudz/shipyard/commit/9281c29099334ae97e244dea7eb63ea1039640ec and made a new release.

**Comment by SSSxCCC** [comment]
I update shipyard version to 0.6.3 and this problem is solved, thanks!
