### ISSUE TITLE
World::clear can not clear all entities

### ISSUE THREAD

**Issue by SSSxCCC** [leudz/shipyard#197]
```rust
let mut world = World::new();

// add 3 entity
world.add_entity(());
world.add_entity(());
let e = world.add_entity(());

// delete 1 entity
world.delete_entity(e);

// call clear
world.clear();

// get entity count
let entity_count = world.run(|e: shipyard::EntitiesView| e.iter().count());

// this prints "entity_count=1"!
println!("entity_count={entity_count}");
```

If world.clear is called after world.delete_entity, there is always an entity left in the world.

shipyard version: 0.6.3

**Comment by leudz** [comment]
Thanks again and sorry you're running into so many errors.
This time it was `Entities::clear` not actually deleting the last entity. It deleted all its components but not the entity itself.
I've released a new version with the fix.

**Comment by SSSxCCC** [comment]
It's ok. I upgraded shipyard to 0.6.4 and it solved the problem. Thanks!
