### ISSUE TITLE
How to get all components of an entity?

### ISSUE THREAD

**Issue by Capytara** [leudz/shipyard#199]
I am developing a game engine that heavily relies on shipyard. My current requirement is to display all components of an entity through reflection in the inspector. How can I get all components of a given entity in shipyard?🙂

**Comment by leudz** [comment]
There is a function called `iter_storages` that will go over all storages in the `World`.
For the introspection part, I'm not sure. You can get the component names easily.
For the struct fields it would be more complicated but you could build a map if you have a list of all your components.

https://github.com/leudz/shipyard/blob/a47e6f6fa276948d804de54f33c940ba27bb77e5/src/all_storages/custom_storage.rs#L171-L203

**Comment by Capytara** [comment]
Thank you, this is exactly what I needed.
