### ISSUE TITLE
Why "last_run" is 0 in first loop?

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#205]
shipyard version: 0.6.2
I found something weird while I was researching `last_insert` and `counter`.

I have three systems.
```
fn add_entities(
    mut entities: EntitiesViewMut
) {
    (1..=5).for_each(|_| {
        entities.add_entity((), ());
    });
}

fn add_first_component_1(
    mut first_components: ViewMut<FirstComponent>
) {
    let first_eid = EntityId::from_inner(1).unwrap();
    first_components.add_component_unchecked(first_eid, FirstComponent(11));
}

fn add_first_component_2(
    mut first_components: ViewMut<FirstComponent>,
) {
    let second_eid = EntityId::from_inner(2).unwrap();
    first_components.add_component_unchecked(second_eid, FirstComponent(22));
}
```

I iterated workloads three times.
```
pub fn run_world() {
    let mut world = World::new();
    world.add_workload(add_entity_workload);
    world.add_workload(first_workload);
    world.add_workload(second_workload);

    world.run_workload(add_entity_workload).unwrap();

    (0..3).for_each(|_| {
        world.run_workload(first_workload).unwrap();
        world.run_workload(second_workload).unwrap();
    })
}

fn add_entity_workload() -> Workload {
    add_entities.into_workload()
}

fn first_workload() -> Workload {
    (
        add_first_component_1,
        ).into_workload()
}

fn second_workload() -> Workload {
    (
        add_first_component_2,
    ).into_workload()
}
```

whenever every system is called, the code below is executed.
https://github.com/leudz/shipyard/blob/master/src/scheduler/into_workload_system.rs#L152-L155

when I print `current` and `last_run`, `last_run` is always 0 in first loop..!
`last_run` is increased from the second loop.

```
// first loop
current: 1, last_run: 0 // add_entities
current: 2, last_run: 0 // add_first_component_1
current: 3, last_run: 0 // add_first_component_2

// second loop
current: 4, last_run: 2 // add_first_component_1
current: 5, last_run: 3 // add_first_component_2

// third loop
current: 6, last_run: 4 // add_first_component_1
current: 7, last_run: 5 // add_first_component_2
```

why `last_run` is 0 in first loop?

**Comment by leudz** [comment]
Tracking works on a range of "time".
In workloads the most important range is `[last_execution..current_execution)` of a system.
So when you use methods like `inserted`, it doesn't return the list of components inserted in the storage from the start of the program. It returns the list from the last time the system ran, up to the current execution.

Having 0 as the initial value is just to have some kind of fake previous execution before the current one.

**Comment by PudgeKim** [comment]
I understand the part "return the list from the last time the system ran, up to the current execution."
But I still wonder what's the purpose of `last_run` is not changed in the first loop.
I also wonder where's the code to prevent changing the `last_run` in the first loop.

**Comment by leudz** [comment]
Okay I think I understand what I didn't explain. 
`last_run` is per system. So there isn't anything preventing it to increase or anything.

It starts at 0. Then every time the system runs `last_run` is updated to `current` value.

> please explain some detail about SparseSet's `last_run`

`SparseSet` doesn't have any `last_run`, do you mean something else?

**Comment by PudgeKim** [comment]
oh sorry I mean `last_insert` in SparseSet. 

`last_insert` is updated when `private_clear_all_inserted` is executed.
and it is used as below 
`last_run.unwrap_or(sparse_set.last_insert),`

But I think.. `last_run` is not None in usual. so what kind of situation `last_insert` is used?

**Comment by leudz** [comment]
`last_insert` is used outside workloads.

Since there is basically no way to have a `last_run`, instead you call `clear_*` to reset tracking. 

Then the range is "last call to clear" up to now.

**Comment by PudgeKim** [comment]
Does "outside workloads" mean  workloads outside of loop?

```
pub fn run_world() {
    let mut world = World::new();
    world.add_workload(add_entity_workload);
    world.add_workload(modify_coordinate_workload);
    world.add_workload(print_coordinate_workload);


    world.run_workload(add_entity_workload).unwrap();

    (0..100).for_each(|_| {
        world.run_workload(modify_coordinate_workload).unwrap();
    });

    world.run_workload(print_coordinate_workload).unwrap();
}
```
In this code, `add_entity_workload` and `print_coordinate_workload` ?

`last_run` is per system so `last_run` will be 0 in `print_coordinate_workload`.
But `current` in `View` `ViewMut` is not per system so when I call `clear_*` I can reset tracking.
Am I right to understand..?

**Comment by leudz** [comment]
Not outside a loop, without using workloads at all. 
You can still access components a few ways. For example `borrow` or `run`.
