### ISSUE TITLE
why insertion_data is not cleared when clear_all_inserted is executed

### ISSUE THREAD

**Issue by PudgeKim** [leudz/shipyard#206]
```
pub(crate) fn private_clear_all_inserted(&mut self, current: u32) {
    self.last_insert = current;
}

```

I just wonder why there's no code to clear `insertion_data`.

**Comment by leudz** [comment]
Clearing the `Vec` would be equivalent to removing the tracking.
Currently this is not possible.

Whenever insertion and modification tracking are active, there is a timestamp for each component.

**Comment by PudgeKim** [comment]
when I run the code below, the size of `dense`, `data`, and `modification_data` are 5 even though four entities are deleted.
```
#[derive(Component)]
#[track(Modification)]
struct Coordinate {
    x: i32,
    y: i32,
}

pub fn run_world() {
    let mut world = World::new();
    world.add_workload(entity_workload);
    world.add_workload(delete_entity_workload);
    world.add_workload(coordinate_workload);

    world.run_workload(entity_workload).unwrap();

    (1..100).for_each(|i| {
        if i == 50 {
            world.run_workload(delete_entity_workload).unwrap();
        }
        if i == 99 {
            println!("hoho");
        }
        world.run_workload(coordinate_workload).unwrap();
    })
}

fn entity_workload() -> Workload {
    add_entity.into_workload()
}

fn delete_entity_workload() -> Workload {
    delete_entity.into_workload()
}

fn coordinate_workload() -> Workload {
    modify_coordinate.into_workload()
}

fn add_entity(
    mut entities: EntitiesViewMut,
    mut coordinates: ViewMut<Coordinate>,
) {
    (1..=5).for_each(|_| {
        let entity_id = entities.add_entity((), ());
        coordinates.add_component_unchecked(entity_id, Coordinate{ x: 1, y: 1 });
    })
}

fn delete_entity(
    mut all_storages: AllStoragesViewMut
) {
    (2..=5).for_each(|inner: u64| {
        all_storages.delete_entity(EntityId::from_inner(inner).unwrap());
    })
}

fn modify_coordinate(
    mut coordinates: ViewMut<Coordinate>,
) {
    (1..=5).for_each(|inner| {
        if let Some(entity_id) = EntityId::from_inner(inner) {
            let mut rng = rand::thread_rng();
            let x: i32 = rng.gen_range(1..=50);
            let y: i32 = rng.gen_range(1..=50);

            coordinates.add_component_unchecked(entity_id, Coordinate{x, y});
        }
    })
}
```

Is this bug? If it's not, what's the purpose?

**Comment by PudgeKim** [comment]
when I run the code below, the size of dense, data, and modification_data are 5 until loop is finished even though four entities are deleted from the 50th loop.

#[derive(Component)]
#[track(Modification)]
struct Coordinate {
    x: i32,
    y: i32,
}

pub fn run_world() {
    let mut world = World::new();
    world.add_workload(entity_workload);
    world.add_workload(delete_entity_workload);
    world.add_workload(coordinate_workload);

    world.run_workload(entity_workload).unwrap();

    (1..100).for_each(|i| {
        if i == 50 {
            world.run_workload(delete_entity_workload).unwrap();
        }
 
        world.run_workload(coordinate_workload).unwrap();
    })
}

fn entity_workload() -> Workload {
    add_entity.into_workload()
}

fn delete_entity_workload() -> Workload {
    delete_entity.into_workload()
}

fn coordinate_workload() -> Workload {
    modify_coordinate.into_workload()
}

fn add_entity(
    mut entities: EntitiesViewMut,
    mut coordinates: ViewMut<Coordinate>,
) {
    (1..=5).for_each(|_| {
        let entity_id = entities.add_entity((), ());
        coordinates.add_component_unchecked(entity_id, Coordinate{ x: 1, y: 1 });
    })
}

fn delete_entity(
    mut all_storages: AllStoragesViewMut
) {
    (2..=5).for_each(|inner: u64| {
        all_storages.delete_entity(EntityId::from_inner(inner).unwrap());
    })
}

fn modify_coordinate(
    mut coordinates: ViewMut<Coordinate>,
) {
    (1..=5).for_each(|inner| {
        if let Some(entity_id) = EntityId::from_inner(inner) {
            let mut rng = rand::thread_rng();
            let x: i32 = rng.gen_range(1..=50);
            let y: i32 = rng.gen_range(1..=50);

            coordinates.add_component_unchecked(entity_id, Coordinate{x, y});
        }
    })
}
Is this bug? If it's not, what's the purpose?

**Comment by leudz** [comment]
It's what is not checked in `add_component_unchecked`.
There is [`Entities::add_component`](https://docs.rs/shipyard/latest/shipyard/struct.Entities.html#method.add_component) to make sure the entity is alive.
