### ISSUE TITLE
Wasm32: Panic "condvar wait not supported" when using Workloads

### ISSUE THREAD

**Issue by Nazariglez** [leudz/shipyard#208]
Hello!

I am experimenting with shipyard to use it on a game, so far has been a great experience. 

There is a little using when using workloads on wasm32, it panics with "condvar wait not supported". It works well if I use `world.run(sys)`. I am not looking for parallel systems running on wasm32, just cross-compilation without changing the code. Is this possible? 

If you guide me or give me a hint I can help with a fix. Thanks!

**Comment by leudz** [comment]
Hi!

You can disable the "parallel" feature by disabling default features and [add back the ones you want](https://github.com/leudz/shipyard/tree/master?tab=readme-ov-file#cargo-features) in your `Cargo.toml`:

```toml
shipyard = { version = "0.7.2", features = ["proc", "std"], default-features = false }
```

**Comment by Nazariglez** [comment]
Oh sure! but then you cannot use `.par_iter` which (unless I am wrong) it's fine for rayon and do nothing on wasm:
--

``` 
error[E0599]: the method `par_iter` exists for tuple `(&View<'_, Boid, Untracked>, &mut ViewMut<'_, BoidV5, Untracked>)`, but its trait bounds were not satisfied
   --> src/main.rs:178:10
    |
177 | /     (&boids, &mut bv5s)
178 | |         .par_iter()
    | |_________-^^^^^^^^
    |
    = note: the following trait bounds were not satisfied:
            `&(&View<'_, Boid, Untracked>, &mut ViewMut<'_, BoidV5, Untracked>): IntoParallelIterator`
            which is required by `(&View<'_, Boid, Untracked>, &mut ViewMut<'_, BoidV5, Untracked>): rayon::iter::IntoParallelRefIterator<'_>`
```

I am probably making something wrong, I'll try to create later a minimal example to test this. Thanks!

**Comment by leudz** [comment]
Oh ok I didn't understand.

The problem is wasm can do parallelism. You can see it here for example: https://wasm-bindgen.netlify.app/exbuild/raytrace-parallel.
You have to setup rayon to use workers instead of os threads but it's possible so I can't disable it on shipyard's side.

Since you said it works fine if you use `World::run` I'm guessing `par_iter` isn't a problem and only the workload is.
What happens if you force it to run sequentially? (instead of calling `into_workload`, you call `into_sequential_workload`)

**Comment by Nazariglez** [comment]
> The problem is wasm can do parallelism. You can see it here for example: https://wasm-bindgen.netlify.app/exbuild/raytrace-parallel.
> You have to setup rayon to use workers instead of os threads but it's possible so I can't disable it on shipyard's side.

It makes sense. 

```rust
Workload::new("run_rules")
        .with_system(sys_rule_one)
        .with_system(sys_rule_two)
        .with_system(sys_rule_three)
        .into_sequential_workload()
        .add_to_world(&world)
        .unwrap();
```
This does the same, `condvar` issue.

**Comment by leudz** [comment]
I'm not too surprised, that would've been too easy 😓

`into_sequential_workload` makes everything runs on the main thread but rayon might still do some setup that doesn't work on wasm. I can completely avoid rayon in that case (I currently don't) but I'd appreciate a reproducible example to check that it actually solves your problem.

**Comment by leudz** [comment]
The new version should fix the problem. You still have to call `into_sequential_workload` but the error should go away.

**Comment by leudz** [comment]
No problem, I'm happy that it works now!
