### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by leudz** [leudz/shipyard#22]
To design an event there are three main questions:
- On **what** the event will be attached?
    - **When** will it trigger?
        - What can it **access**?

- Storage (except unique<sup name="a1">[1](#f1)</sup>)
    - on creation, after the component has been inserted
         - id + entire storage for sequential
         - id + reference to the component for parallel
    - on removal/deletion
         - id + component + entire storage for sequential
         - id + the component for parallel
    - on modification<sup name="a2">[2](#f2)</sup>
         - id + entire storage for sequential
         - id + reference to the component for parallel
- Pack (in theory)
    - on creation, after the component has been inserted
         - id + entire pack for sequential
         - id + reference to the components for parallel
    - on removal/deletion
         - id + entire pack for sequential
         - id + the components for parallel
- Pack (in practice)
-> it would require reordering tuples or returning `Box<dyn Any>`, they both seems terrible.
- System
-> make it part of the system
- Workload
-> make it a system
- Pipeline
-> make it a workload

Listeners could also be useful but the only way I can see to implement them is to require them when adding/removing components like a pack. There might be a better way.

<sup name="f1">1.</sup> Unique storages don't store component nor entity so they can't be eligible for creation nor removal/deletion and see <sup name="a2">[2](#f2)</sup> for modification. [▲](#a1) 
<sup name="f2">2.</sup> Tracking modification isn't possible as far as I know, checking if the bits changed for example doesn't work if the component go back to its original value before the end of the iteration. So modification events will trigger after every mutable access, whether or not a change happened. [▲](#a2)

**Comment by dakom** [comment]
Might be worth looking at [signals](https://github.com/Pauan/rust-signals) as a possible choice here

>A game engine can use Signals to automatically update the game's state whenever something changes.

**Comment by leudz** [comment]
We likely can't use it directly but I'll look into it
