### ISSUE TITLE
Add the ability to retrive components from AllStorages

### ISSUE THREAD

**Issue by leudz** [leudz/shipyard#29]
There's no established plan but it'll happen one way or another.

**Comment by dakom** [comment]
use case to keep in mind: 

* have a `Unique` storage that holds an event queue
* process that queue in the ECS 100%
* some events want to modify `AllStorages` (e.g. to remove an entity)

therefore a system needs to borrow other components and AllStorages at the same time - for starters, only `Unique` components, but it'd be great if it could be any.

**Comment by dakom** [comment]
nm - need more than Unique ;)
