### ISSUE TITLE
Components Bundle

### ISSUE THREAD

**Issue by leudz** [leudz/shipyard#36]
I just discovered the [component_group crate](https://github.com/sunjay/component_group), a crate to work on groups of components in specs.

I thought of something similar a while ago but I was and am still a bit worried this pattern will be misused. One of the big strength of an ECS is being able to mix and match components, sometimes even in surprising ways. This pattern goes against this but provides some big pluses.

The first thing required would be a proc macro to generate all code related to a bundle:
```rust
#[bundle]
struct Virus {
    #[NonSend] // just as example
    position: Position,
    size: f32,
}
```

Two different implementations have been proposed, both would  generate these structs used for iteration and `get`:
```rust
struct VirusRef<'c> {
    position: &'c Position,
    size: &'c f32,
}
struct VirusMut<'c> {
    position: &'c mut Position,
    size: &'c mut f32,
}
```

The two methods differ for the views and iterators, method 1 generates a new type for each bundle while method 2 uses a `BundleView[Mut]` and `BundleIter[Mut]`.

For the first method these structs would be generated:
```rust
struct VirusView<'v> {
    position: NonSend<View<'v, Position>>,
    size: View<'v, f32>,
}
struct VirusViewMut<'v> {
    position: NonSend<ViewMut<'v, Position>>,
    size: ViewMut<'v, f32>,
}
```

It'll be possible to access the inner views through the bundle. With method 1 it would be a field access, with method 2 a `TypeId` lookup.

I tried to implement both methods but rust-analyzer handles method 1 terribly while method 2 requires GAT or specialization.

**Comment by colelawrence** [comment]
Related to #78
