### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by leudz** [leudz/shipyard#48]
I thought [typetag](https://github.com/dtolnay/typetag) was the right tool to implement this issue but I'd also need specialization. Since this isn't happening anytime soon and it likely wouldn't fit all use cases here's another approach.
I didn't try to implement it so it might be impossible to get to compile 😄 

To me there's two use cases for ser/de:
1. saving (part of) a `World` and loading it
2. saving (part of) a `World` and adding it another one

The first one basically has no issues tied to it, the second one has a few:
- what happens if the entity already exists?
- what happens if the entity already has a component of this type?

I don't think a single behavior will fit all use cases so making both serialization and deserialization as modular as possible is the only way to go.

This issue is a big one but all methods don't have to be implemented at once. With this pattern adding new methods won't be a breaking change as long as the serialization format doesn't change.

## Serialization

The builder pattern seems a good way to go about it:
```rust
world.serialize::<View<T>>(serializer).build();
```
`serialize` would work with `Borrow` so any view that can be requested by a system could be used here.
It has to be a view and not a simple type for differentiating unique storage and `!Send`/`!Sync` components.
`T` would have to implement both `Serialize` and `Deserialize` of course.

This would serialize the whole view, then you could filter:
```rust
world.serialize::<View<T>>(serializer).filter(|t: &T| -> bool { /* do your filtering */ }).build();
```
```rust
world.serialize::<View<T>>(serializer).filter_with_id(|(id, t): (EntityId, &T)| -> bool { /* do your filtering */ }).build();
```
```rust
world.serialize::<(View<T>, View<U>)>(serializer).complex_filter(|(t, u): (&T, &U)| -> (bool, bool) { /* do your filtering */ }).build();
```
As opposed to `filter`, `complex_filter` returns a `bool` per component.
```rust
world.serialize::<(View<T>, View<U>)>(serializer).complex_filter_with_id(|(id, (t, u)): (EntityId, (&T, &U))| -> (bool, bool) { /* do your filtering */ }).build();
```
```rust
world.serialize::<View<T>>(serializer).without_shared().build();
```
```rust
world.serialize::<View<T>>(serializer).custom().build();
```
I explain this one in the section below.

There probably will be some additional generics on `serialize` so a few `_` to add.
Using multiple filters would be an error, there will be a `try_` and panicking version.

## Deserialization

```rust
world.deserialize::<View<T>>(deserializer).build();
```
The default behavior will be to create a new entity for entities that already exists.
```rust
world.deserialize::<View<T>>(deserializer).checked_entities()?.build();
```
Will first go through all entities and if one of them already exists it'll return an error with the id.
```rust
world.deserialize::<View<T>>(deserializer).skip_entities()?.build();
```
Will skip any entity that already exist.
```rust
world.deserialize::<View<T>>(deserializer).checked_components()?.build();
```
It'll first check all storages to see if an entity has a component that will be deserialized and return an error if it has with the `EntityId` and the component `TypeId`.
```rust
world.deserialize::<View<T>>(deserializer).add_components().build();
```
If the exact entity exist it'll add the components to it if it doesn't have one. If the spot is taken by an entity with a different generation it'll skip it.
```rust
world.deserialize::<View<T>>(deserializer).replace_components().build();
```
If the exact entity exists and already has some of the components to be deserialized, it'll replace them.
```rust
world.deserialize::<View<T>>(deserializer).custom().build();
```
I'm not sure what arguments this one will take. Here's the use case I imagine:
You have a tree inside the ECS and are using `EntityId` to link nodes. You want to transfer this tree to another `World`.
There's no way to do it properly with the methods above. If you skip entities, you'll have holes in the tree. If you use `check` it'll work sometimes and sometimes it won't. With `new_entity` your tree will be a mess.
`custom` would allow you to have a context and allow powerful operations on storage. For example you could ask which entity is the last one. Going from here you can safely offset all your nodes and it'll end up correct.
I imagine this will require a few new views that let you more in control of entity and component creation.

It could also be used to reset entities' generation when loading a fresh `World`.

**Comment by svenstaro** [comment]
What's the status of serialization in 0.5? I'm implementing a network game and would basically need to individually send changed components and then somehow on the receiving side integrate that sent component into an existing entity via known global ID somehow. Is this currently easily doable in shipyard?

**Comment by leudz** [comment]
As opposed to what I said almost a year ago, 0.5 doesn't change much on the serialization front.
The goal of this issue was to provide a few highly customizable methods to take care of serialization. But I'm not sure it's the right path anymore.
Recently I've been thinking about not adding code but recipes to the guide.

That being said, serialization is possible and I don't think it's too complicated.
I've made [a small gist](https://gist.github.com/leudz/53de6d096680b9bd24df4bd65e3f7809) that shows a lot of what you're describing.
I used [laminar](https://github.com/amethyst/laminar) for the networking because of its simple api.
The main thing I'd change to make it faster would be to send multiple components in each packet and not borrowing storages in a tight loop.

Don't hesitate to ask any question regarding the gist or anything else.

**Comment by leudz** [comment]
Having `shipyard` handle serialization would be complicated and limiting. There is just too many ways to serialize a `World`.
A lot of pieces have been added over the time to allow `EntityId`s, entities and storages creation on the user side.
I think this where serialization should be designed.
