### ISSUE TITLE
Make the system proc-macro emit a compile time error if borrowing AllStorages together with another storage

### ISSUE THREAD

**Issue by Veykril** [leudz/shipyard#64]
It might be that I just misunderstood something, but if I'm not mistaken borrowing `AllStorages` together with any other storage in a system will always lead to a panic due the other storage also being borrowed from world, while world already has everything borrowed from it.

Example that will always lead to a panic
```rust
#[system(FooSys)]
pub fn run(stores: AllStorages, foo: &Foo) { ... }
```
A simple workaround to this is of course to only take stores, and manually borrow `&Foo` from stores afterwards. I think it would be nice for the proc-macro to reject this code at compile time and maybe even hint the possible workaround as a helpful insight.

I wouldn't mind implementing this, just wanted to ask upfront whether this is wanted(and whether I understood the problem correctly here) 😄 

Edit: The docs should probably also mention this.

**Comment by leudz** [comment]
It'll panic or return an error based on the function that calls the system but you're absolutely right, it'll never run.

Having the error at compile time would be a great addition! There's just one thing that can be borrowed at the same time as `AllStorages`, the thread pool.

If you don't mind working on it, it would be awesome! I'm here if you have any questions.

The guide explains it but not the docs... I added it to my to-do list, thanks for pointing it out.
