### ISSUE TITLE
Feedback after doing a refactor from Legion to Shipyard

### ISSUE THREAD

**Issue by almetica** [leudz/shipyard#70]
Hi,

I wanted to give some (hopefully constructive) feedback about your ECS shipyard. Currently I'm writting an alternative server implementation for a MMORPG that uses multiple ECS to handle the game logic (One variable tick ECS for the "global" server wide events like trading, chat, login handling etc and multiple high tick ECS for the local fields and dungeon instances that handle combat, player movement, colloision detection, view curling etc).

Since I work with legacy software which network code I can't change, I'm stuck with the logic that the client is dictating in some way. So my client needs to know the 64bit EntityId to desribe in world objects (like players, NPCs, projectiles etc). I first chosed Legion as the ECS to use, but soon found out that my above requirement of serializing/deserializing the EntityId wasn't possible with Legion.

So I had to rip out the ECS code and replace it with Shipyard. After around 12 hours of refactoring and getting all my tests running again, I think I have to share some valuable feedback:

The positives:
- The documentation is quite good. Especially the API documentation is very helpful (something were Legion is lacking in comparison) and also the guide helped a lot to understand the implementation. I would maybe suggest a glossary. In my first discovery I dismissed Shipyard as not ready because I thought it would lack "Resources". I now know that `Unique` provides this feature, but it wasn't apparent right away.
- The demonstration code was very helpful to understand on how to use the API.
- Writing Systems and Components is quite hassle free. I easily could transfer my ECS code from Legion to Shipyard, so they are pretty comparable in the feature set, I guess.
- ```World.run()``` is a life safer when writing tests. It helps a lot to contain the borrowing and no needing to wrap every code with blocks or use ```drop()```. I kind wish that ```AllStorages``` would have a comparable method.

The negatives:
- I was caught offguard that the Shiperators are not normal std iterators.
- Deletions of entities are a hassle to do in systems. Since you have to borrow from ```AllStorages```, your code gets more complicates. I solves this problem, by queuing my entities in a unique vector and have a special "cleaner" system to delete them at the end of a tick. Legion has command buffers which are quite useful in these cases.
- Since I use an event as a component messaging system, I delete all of my events at each tick. A "delete all entities with this component" method would be helpful (maybe it could also be implemented more efficient?).
- The system procedural macro has too much magic. Since it shadows the real type of the storages, it makes reading the code much harder then it needs to be. My IDE also gets confused by this. Let me elaborate:

<img width="358" alt="shipyard-1" src="https://user-images.githubusercontent.com/50792179/79046836-71947900-7c13-11ea-8bc6-ac230b4d57f8.PNG">

Somebody who doesn't know how the system macro works in depth would assume that the above storages are somehow just a reference / mutable reference of the component. But actually ```mut outgoing_events: &mut OutgoingEvents``` is a ```mut outgoing_events: ViewMut<&OutgoingEvents>``` and if you would want to declare the signature of a method that would like to use that View, you would need to declare it like this:

<img width="305" alt="shipyard-3" src="https://user-images.githubusercontent.com/50792179/79046929-e8ca0d00-7c13-11ea-8a35-7fb17cfc6905.PNG">

My IDE also can't handle this (which isn't my primary concern):

<img width="403" alt="shipyard-2" src="https://user-images.githubusercontent.com/50792179/79046921-dc45b480-7c13-11ea-9b1a-fce9b662c09c.PNG">

I personaly think that code should be easy to read and easy to understand. This kind of magic might saves some characters to type, but makes understanding the code much harder. This also makes the API look inconsistent, since you have to use write ```Unique<&Component>``` when you want to use ```Unique``` components anyway.

Other things I would like to see:
- I really like the idea to have an "universe" from which you could create multiple worlds that share the EntityId space between them. Especially in a multi-instances environment like my project it would help simplify some logic.

So much for my feedback. Hopefully you find it helpful. You can close this issue on your own discretion.

Please keep up the good work.

**Comment by leudz** [comment]
Hi! Thank you so much, feedback is very useful!

- I'll add a sentence to the doc to make it show up when looking for "Resources". There's also plans for a cheat sheet, it'll be useful in this case to quickly see all features.

- Regarding `run` it makes sense to add it to `AllStorages` and wouldn't be too much work.

- One of the feedback I had when releasing 0.3 was "try to avoid glob imports in examples", and while I disagree in that case, I thought about it and I'll make `use` apparent in all doc examples. This should make it less of a surprise.\
There was also a version of the iterator chapter in the guide that explained it in detail, I removed everything but there should at least be a sentence stating that `Shiperator` is used for iteration and not `std::iter::Iterator`.

- I think it could work well with #43 (I just notice there's no description).\
This function is meant to be used every frame or every few frames to do some cleanup. It'll likely be configurable to not be forced to pay for a full cleanup every frame.\
Making a list of entities to delete could look like this:
    ```rust
    #[system(BulletRemoval)]
    fn run(
        bullets: &Bullet,
        collision_manager: &CollisionManager,
    ) {
        bullets
            .queue_deletion(|bullet| collision_manager.has_collided(bullet));
    }

    let world = World::new();
    world.borrow::<&mut Bullet>().queue_pack();
    /*
    add a few systems, run them
    */
    world
        .maintain()
        .delete_entities();
    ```
    And you don't always have to borrow `AllStorages` to delete entities. While this is the default and simplest way to do it, you can use `Entities::delete_unchecked` if you know which components your entity has (or could have). You only need to borrow these components and `Entities` exclusively.
- In theory you can already make it as a user but I could add a more ergonomic way to do it. This is assuming you don't know the components your events can have:
    ```rust
    #[system(DeleteEvents)]
    fn run(all_storages: &mut AllStorages) {
        let mut events = AllStorages.borrow::<&mut Event>();
        let mut ids: Vec<_> = events.ids().collect();
        events.clear();
        drop(events);
        for id in ids {
            all_storages.delete(id);
        }
    }
    ```
    Ergonomic way:
    ```rust
    #[system(DeleteEvents)]
    fn run(all_storages: &mut AllStorages) {
        all_storages.delete_any_with::<(Event,)>();
    }
    ```
- I don't think it's a problem with the macro, `run` and `borrow` also use `&(mut) Component` to borrow storages. Even in the expended version `View` and `ViewMut` don't have to be there:
    <details>
    <summary>Expended version</summary>

    ```rust
    struct ConnectionManager;
    impl<'sys> System<'sys> for ConnectionManager {
        type Data = (
            &'sys EcsEvent,
            &'sys mut OutgoingEvents,
            &'sys mut Connection,
            EntitiesMut,
            Unique<&'sys mut ConnectionMapping>,
            Unique<&'sys mut DeletionList>,
            Unique<&'sys WorldId>,
        );
        fn run((
            incoming_events,
            mut outgoing_events,
            mut connections,
            mut entities,
            mut connection_map,
            deletion_list,
            world_id,
        ) = <Self::Data as SystemData<'sys>>::View) {}
    }
    ```
    </details>

    I 100% agree with:
    > Somebody who doesn't know how the system macro works in depth would assume that the above storages are somehow just a reference / mutable reference of the component.

    > code should be easy to read and easy to understand
    
    But we don't get to the same conclusion.

    To me, the macro (and the other functions) use just the right amount of information to understand at a glance what is been borrowed and how. Even your IDE helps by making `mut` very visible. With `View`/`ViewMut` you wouldn't have that.\
    It would be clearer that you're borrowing something else, but you already know that if you're using the library. If you're reading the code without knowing anything about shipyard, you probably won't understand what a `View` is either.
    
    Funny thing about `Unique`, you get a `UniqueView<WorldId>`. It's consistent from my point of view, there's the borrow `&(mut) Component` and a "modifier", `Unique` in this case. It could also be `Send`,... Other might be added later or removed when specialization is added, we'll see in a few years 😄.

    In a previous iteration of the borrow chapter there was an exhaustive list of all possible borrow and the type returned when borrowing them. It got removed since it's the second chapter and having a list of 20 types you never seen wasn't great. This list should be somewhere though, I haven't found the right place yet. The cheat sheet could be a good idea.

- I could make a `SharedWorld` struct identical to `World` except entities would be stored in `Arc<Entities>`. I suppose in this case when entities are deleted it would be across the whole "universe". This likely can't work very well without #43 or something like it. Deletion would only happen at sync points, except with an `_unchecked` method.

    There's also plans for systems borrowing storages from multiple worlds (not soon but someday).

Again, thank you and I hope your project goes well.

**Comment by almetica** [comment]
@leudz 

The ```.queue_deletion()``` sound promising.

I really like the idea of your ergonomic approach to delete all entities with a component:
```all_storages.delete_any_with::<(Event,)>();```

> To me, the macro (and the other functions) use just the right amount of information to understand at a glance what is been borrowed and how. Even your IDE helps by making mut very visible. With View/ViewMut you wouldn't have that.
It would be clearer that you're borrowing something else, but you already know that if you're using the library. If you're reading the code without knowing anything about shipyard, you probably won't understand what a View is either.

But here is the thing: I actually don't see what I'm getting (you are not getting a immutable/mutable reference to a component, you get a View into the storage, which could be immutable/mutable). The function signature is actually lying to me. I personally find that highly confusing.

```run()``` and ```borrow()``` are returning the right types and don't lie to me. Their function signature matches their behavior:
```rust
fn borrow<'a, C: StorageBorrow<'a>>(&'a self) -> <C as StorageBorrow<'a>>::View
````

I don't want to change your view on this matter. I'm just saying that it's highly confusing for somebody not knowing the macro and highly unintuitive even when re-reading the code just moments later. Maybe I will just copy your macro and rewrite it for my special need.

Ohhhh before I forget it again... I personally had another requirement, which is honestly very special for server programming and won't interrest 95% of the client code:

Async/Await support when running systems. Like I stated above, I have a special ECS that runs in "variable tick rate" mode, and is kinda running the code, that involves IO so that the instance ECS can run as fast as possible. So having support for running in an async environment (like tokio or async-std) would be helpfull if you are talking with the database in a system and might want to parallize it as much as possible. But I totally understand that this change would most likely be massive and is kinda special in my case.

Thank you again for reading my feedback.

**Comment by leudz** [comment]
We have different views (haha) on the subject, it happens. I won't implement another macro but I'll happily help you modify the existing one if you need.

Async/await is somewhat planned, I might need it too at some point. With the current scheduler it's not possible since it builds an "execution model" when you add workloads.
It'll change completely with #44. This will basically make async/await just for storages, then it'll be a lot easier to add async/await for external things like network/db/...

I think I'll have to make my own runtime since `!Send` and `!Sync` have a "thread affinity" and it'll hve to work on both storage and io levels, I don't know if I could make something like this with an existing runtime. I'll very likely use part of existing runtimes though.

As you guessed this will be a massive change. The change in the scheduler won't directly affect the API but rayon might be replaced. Async/await will just add a new `AsyncSystem` trait and 
using `async` in the macro will work.
```rust
#[system(ThisOneIsAsync)]
async fn run() {}
```

**Comment by almetica** [comment]
If you make your own async runtime, keep in mind that you might break the support for already existing async libraries (like http server, database driver etc). We currently have like three big runtimes and they are not really compatible with each other: actix, async_std and tokio.

This means, that existing libraries need to implement support for a given a runtime. For example, mysql_async only support tokio and sqlx only support async_std and tokio, but not actix.

It's currently a mess and I wish there would emerge a proper standard (https://xkcd.com/927/).

**Comment by leudz** [comment]
My knowledge on async/await is very theoretical, but isn't it possible to make my own reactor and executor and still be able to accept tasks meant for one other runtime.
I'll have to make the part I replaced work nice with the part I don't replace of course. And users will use the types provided by this existing runtime.

If this isn't possible I might be able to embed a full runtime but this would be a lot messier.

**Comment by almetica** [comment]
I think it's actually not possible to simply switch runtimes, at least from my initial tests. As soon as IO is involved, things get messy, since you have to use the async IO routines from the runtime you are using. And async without IO is kinda missing the point.

You could take a look at the sqlx codebase for a reference what is needed to support many runtimes by a library (the codebase is quite small).

Good search terms should be ```feature = "runtime-async-std``` and ```feature = "runtime-tokio```.

**Comment by leudz** [comment]
I'm not planning to support multiple runtimes. It might be possible but that would be lot of work with diminishing returns.
Like you said, currently there's three main ones, so I'd pick one of the three, after looking into it in depth.

Let's say tokio, what I'd like to do is keep some part of it and adapt some others to work well with storage scheduling. As a user, it would be just like talking to tokio but under the hood it wouldn't be tokio but a mashup of tokio and shipyard's scheduler.

I just hope it's possible 😄.

**Comment by dakom** [comment]
Disclaimer: I don't know enough about all the runtimes, where the line is between executor and runtime, etc.

Just as like a point of interest to keep in mind - when targeting wasm for browsers, the blessed solution uses the [wasm-bindgen-futures](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/futures) crate to pass it over to the JS runtime (i.e. to execute via JS Promises). I'm not entirely sure if/how/why tokio doesn't work in a web environment, though it may have to do with the nuance of how JS blocks and schedules things in its own "microtask queue", and doing async _without_ JS promises would maybe give unexpected results like tying up the Browser's UI thread in weird ways.

So, if it's possible, keeping this use-case in mind would be great. Just in case the problem wasn't hard enough ;)

**Comment by almetica** [comment]
@leudz I'm not suggest that you should support many runtimes, but to just look into what it takes for libraries to support multiple runtimes, so that you understand what the current hurdles are to properly implement async/await. 

I think it boils down to one point: STD doesn't implement any async IO yet but only gives people the primtives to build async code. But async code without proper IO implementation is kinda useless, since that's kinda the raison d'etre for async code.

But anyhow, I'm looking forward to your idea on how to implement async/await in your ECS. I'm currently implementing the code so that I could switch easily to async down the road and could test your implementation (I'm currently targeting tokio on my network frontend of the server, since they implemented a greatly improved ```select``` macro, which is highly desirable when writing concurrent code).

**Comment by leudz** [comment]
@dakom I just read https://github.com/rustwasm/wasm-bindgen/issues/1126 too and a few links in there. The Rust side must rely on JS's event loop which is very interesting.
If I support the web, I can't control the loop, it's like inputs. Embedding other runtimes the same way could make sense... 🤔
Shipyard's runtime would become a very slim wrapper and rely on the runtime set in the cargo feature to do all the heavy lifting. If storages borrow and "thread affinity" can work this way, doing more work on my side might become an optimization.

@almetica Ok I'll make sure to look into it, right from the readme having exclusive feature isn't that great 😄

Great! It's not on the "soon™ to-do list" but #44 might get there in the close future. It's an interesting feature and I'm curious to see how it'll turn out.

**Comment by dakom** [comment]
I'm sure you noticed - but just in case, that wasm issue is a _little_ bit old in terms of async/await, so for example a lot of the earlier points were discussions in the context of futures 0.1 or what might happen as it transitions to 0.3. It's a great topic and there's some wonderful gems in there (as well as my confusion 😅 ), but I think the current story might be a little clearer from looking at wasm-bindgen-futures with fresh eyes. Just a heads up!

**Comment by zicklag** [comment]
Also something to look at is [agnostik](https://github.com/bastion-rs/agnostik) which is a layer around other async executors to help you write executor agnostic code.
