### ISSUE TITLE
View naming simplification

### ISSUE THREAD

**Issue by cart** [leudz/shipyard#77]
This one might be controversial but I figured I'd give it a shot anyway.

Now that the "view" types are the primary api users interact with, I think it might make sense to give them shorter / less noisy names. I understand that this actually clashes with the "backing" types in some cases, but I think the public api should take priority on "name clarity" and ergonomics.

| Current          | Alternative 1 (Read/Write)     | Alternative 2 (Mut)|
|-----------------|-------------|-----|
| View                    | Read        |    View |
| ViewMut             | Write       |  ViewMut|
| EntitiesView       | EntitiesRead   |   Entities|
| EntitiesViewMut | EntitiesWrite | EntitiesMut|
| UniqueView        |       UniqueRead      |  Unique|
| UniqueViewMut | UniqueWrite |UniqueMut|

My personal preference is for **Alternative 2 (Mut)** . It cuts down on line noise significantly, maintains compatibility in the "View" case, and still lines up nicely with rust "mut" semantics.

**Comment by leudz** [comment]
The backing type is in the public api now and is quite visible in the documentation.

![image](https://user-images.githubusercontent.com/45027362/80275070-3ef08300-86df-11ea-91f1-d95e9f1c148b.png)

I'm strongly against Alternative 1 since it's not what it means:
```rust
fn main() {
    let world = World::new();
    world.run(|usizes: View<Mutex<usize>>| {
        *usizes.iter().next().unwrap().lock().unwrap() = 0;
    });
}
```

While it's also true for Alternative 2 (and the current names), it's what Rust chose.
I don't think it's worse loosing name clarity in this case. As always, I'm willing to be convinced but it hasn't happened yet =)

You can always do it locally by creating a module and aliasing the name like you want.

**Comment by colelawrence** [comment]
If we are just gathering opinions, I believe that the current names are much more clear for understandability than either suggestion made.

`View` is an important name that helps a user importing `shipyard::*` distinguish and group "View" types together.

It has also greatly helped me establish strong explicit names for my arguments by being able to prefix views with `v_` and ViewMut with `vm_`

Here's an example of the signature from one of my systems.
```rust
pub fn editing_edits(
    (entities, v_editor, mut vm_q_edit_cmds, mut vm_prose): (
        EntitiesViewMut,
        View<Editor>,
        ViewMut<QueuedEditCommands>,
        ViewMut<Prose>,
    ),
) {
    // here, v_editor is very clear what it can provide
    for (editor, q_edits) in (&v_editor, &mut vm_q_edit_cmds)
        .iter()
        .filter(|(_, cmds)| cmds.0.len() > 0)
        .into_iter()
    {
    // ...
```

**Comment by cart** [comment]
The "view" conceptual grouping is definitely valuable. Additionally, I clearly didn't look into the api enough because i didnt realize that EntitiesView deref-ed into Entities.

The distinction between "view" and "core type" could be re-established by a rename of the core types: ```Entities``` -> ```EntityStorage```. Which then frees up anything that doesn't end in "Storage" (ex: ```Entities```) to be the reference type.

I also think the "view" concept is implicit. If everything in a system's function signature is a view, then theres no need to double down on that information. I suspect that most legion users will only ever directly interact with the view types. Do they really need the View/Storage distinction to be a core part of their experience? 

However this is another case of personal preference. I'm happy to defer to @leudz's aesthetic choices here. You can't please everyone and I'm sure you'll get another post at some point asking for something different :smile:

**Comment by leudz** [comment]
It would be a bit weird with `AllStorages` though 😄

> If everything in a system's function signature is a view

This might change in the future, I talked about having returned types go from one system to another in workloads for example.

> legion users

*shipyard 😆
The distinction between view/view mut and storage is the same as reference/mut reference/owned.
And views technically don't have to be over the whole storage. So it's a bit like slice and `Vec`.

I think I'll stick to the more explicit names, once you understand the concept, you're free to go with any names you want in your codebase.

**Comment by cart** [comment]
Cool thats all satisfactory to me :)

> legion users

bawhaha i sure goofed on that one didnt I :smile:

**Comment by colelawrence** [comment]
@cart thanks for the follow-up points. I really enjoy the back and forth a on these kinds of topics. I wanted to add that even though system fn arguments all take some form of "*View*", my reuseable functions benefit from the distinction as well. In a few places in my current project, I have broken out complex component updating logic into helped functions that take both "*View*" arguments and other types of params.

Like this:

```rust
enum MoveDirection {
    Up,
    Down,
}
fn move_cursor(
    v_child_of: &View<ChildOf>,
    v_ordered: &View<Ordered>,
    mut cur: &mut EditorCursor,
    dir: MoveDirection,
) {
    ...
```
