### ISSUE TITLE
Ported demo to Seed

### ISSUE THREAD

**Issue by MartinKavik** [leudz/shipyard#79]
Hi!
I've just ported your demo to Seed - [bunnies example](https://github.com/seed-rs/seed/tree/master/examples/bunnies). Works great!
The reason was this [question](https://seed.discourse.group/t/integrating-seed-app-with-ecs/67) on Seed's forum.

----

I've removed some lower-level code, done smaller refactors (like using `SmallRng` instead of `ThreadRng`) and I plan to do a bigger refactor in the future because many parts of the code trigger clippy errors.

Questions: 
 - Should I add your `MIT` license into that Seed example?
 - Can I add it to Seed website / README as an example of a game written in Seed/Shipyard?
 - Do you plan to add a simpler example to demonstrate the basic Shipyard functionality? - I think it would help to people like the guy who created the question on the Seed forum.

Thank you!

**Comment by leudz** [comment]
Hi! It looks great!
They asked it [on the users forum](https://users.rust-lang.org/t/shipyard-0-4-release/41553/2) too but I didn't have any example or person to point to, I'll have next time 😃 Thank you!

- I'd say no need but I didn't write the demo, let's summon @dakom just in case.
- Of course, can I add a link too?
- There's a [guide](https://leudz.github.io/shipyard/book) that explains all major functionalities. It just lacks a small game tutorial.

**Comment by MartinKavik** [comment]
> I'd say no need but I didn't write the demo, let's summon @dakom just in case.
   - Ok, feel free to close the issue when you want.

> Of course, can I add a link too?
  - Sure.

> There's a guide that explains all major functionalities. It just lacks a small game tutorial.
  - Well, as somebody who doesn't have experience with game development and ECSs, I wouldn't be able to write anything in Shipyard until I find the demo - I understand samples / API docs in the guide but I have no idea how to compose them together.
  - We have the same "problem" in Seed - many users fight with architecture / best practices / patterns because they don't know Elm architecture or they are new to web development. So I'll try to rewrite Seed website to tutorial-like guides / docs. (Just a tip).

**Comment by leudz** [comment]
You're right, the guide (especially in it's current state) isn't enough to learn how an ECS fits in a program.

Luckily for me, there's already a big tutorial ([roguelike tutorial](https://bfnightly.bracketproductions.com/rustbook/)). I've been thinking about translating it, it's a big task but could be a good solution.
The recipe section should also receive additions in the future for smaller building blocks.

Documentation is hard 😄
And good luck with your rewrite!

**Comment by dakom** [comment]
From my perspective the demo was just a basic starting point, and I originally ported the concept (and stole the artwork) from PIXI... definitely no need to credit me and I don't think there's any licensing issues whatsoever but I'm not a lawyer :) 

(anecdotally, over the years I used that "bunnymark" idea for various things and was in touch with the PIXI team in some version of it... I think [this react reconciler test](https://dakom.github.io/react-renderer-test/), they were always cool with it and happy to see other approaches to the same test):
