### ISSUE TITLE
Tracking down memory usage in shipyard?

### ISSUE THREAD

**Issue by djahandarie** [leudz/shipyard#84]
I'm using shipyard in a WASM app, and a lot of entities get created and deleted (tens of thousands with pretty hefty structs as components). I *think* I'm deleting everything I should be, but there's a pretty clear memory leak somewhere at the rate of 100MB/s.

Since I have a lot of different component types (~25) it's annoying to write something which goes through all of them to count number of entries etc.

Is there any generalized solution I can use to inspect shipyard's dataset and how much memory each storage is using, etc.?

**Comment by leudz** [comment]
That's weird, I'm not doing any `unsafe` trick with insert/removal.

There's nothing implemented to inspect how many component you have in total or which type they have. The only useful method is `len` and do that for every component type.

I'm looking into it on my side to see if I can spot something.

**Comment by leudz** [comment]
Just tried basic tests with and without miri but no memory issue.

**Comment by djahandarie** [comment]
Thanks for checking! 🙏 I think it’s likely not an actual memory leak but rather that I have a poor understanding of exactly how much memory entities/components use in shipyard and I just need extra visibility into that. I think this is just an overall issue with the WASM profiling toolchain and not necessarily a shipyard issue (though there are some shipyard-internal utilities one could imagine to help.)

Let me just drop a reference to issue #52 to track this as another use case of entity or storage iteration and close out this issue.

**Comment by leudz** [comment]
Shipyard uses 8 bytes per entity and 8 bytes plus `size_of::<usize>()` per component.
I'm using vectors almost everywhere so memory used will be more than that.
Storage also allocates in buckets so here too it's not very accurate.
There's also some memory per storage for locks,...

I'll make a function to print a report, as long as there's no leak it'll display everything.
