### ISSUE TITLE
Double buffering

### ISSUE THREAD

**Issue by poconn** [leudz/shipyard#94]
Any interest in adding this?
[EnTT post](https://skypjack.github.io/2019-02-25-entt-double-buffering/)
Something like the following:
```rust
fn update_my_component(cs: View<MyComponent>, new_cs: ViewMutBuffered<MyComponent>) {
    for (c, new_c) in (cs, new_cs).iter() {
        new_c.write(c.update());  // fn update(&self) -> Self
    }
}

world
    .add_workload("workload")
    .double_buffer::<MyComponent>()
    .with_system(system!(update_my_component))
    .with_system(system!(|cs: View<MyComponent>| {
        for c in cs.iter() { assert!(c.is_old()); }
    }))
    .swap_buffer::<MyComponent>()
    .with_system(system!(|cs: View<MyComponent>| {
        for c in cs.iter() { assert!(c.is_new()); }
    }))
    .build();
```
Alternatively, I think it could be done with a single view that derefs to `&old_value` or `&mut new_value` (cloning the old value to populate the buffered storage the first time this is called) to allow for calling `&mut self` methods on the component, although not sure I like that idea.

Anyway I haven't really thought that through, just spitballing. I'm happy to try implementing it myself, just looking for other opinions on the interface and whether it should even be added.

Thanks!

**Comment by leudz** [comment]
This is a bit weird:
```rust
for (c, new_c) in (cs, new_cs).iter() {
    new_c.write(c.update());  // fn update(&self) -> Self
}
```
What would be the type of `new_c`?

I'm not against the feature but I think I would prefer it this way:
```rust
fn update_my_component(cs: View<MyComponent>, mut new_cs: ViewMut<Buffered<MyComponent>>) {
    for (id, c) in cs.iter().with_id() {
        new_cs.add_component_unchecked(c.update().into(), id);
    }
}

fn swap_buffer<T>(mut ts: ViewMut<T>, mut new_ts: ViewMut<Buffered<T>>) {
    ts.swap_buffer(&mut new_ts);
}

world
    .add_workload("workload")
    .with_system(system!(update_my_component))
    .with_system(system!(|cs: View<MyComponent>| {
        for c in cs.iter() { assert!(c.is_old()); }
    }))
    .with_system(system!(swap_buffer::<MyComponent>))
    .with_system(system!(|cs: View<MyComponent>| {
        for c in cs.iter() { assert!(c.is_new()); }
    }))
    .build();
```

It's more verbose on the user side but there is less code specific to this feature.

**Comment by poconn** [comment]
Yeah on second thought I agree with your approach, the reduced user code from what I had in mind probably isn't worth the inconsistency with the existing interface. Currently the ergonomics of doing this externally aren't too bad, the main reason to add support from shipyard would be if the swap could be done much faster.

Speed isn't a huge issue for my current use case so I'll probably hold off on this, but I might be interested in coming back to it later. I'll leave it up to you whether it's worth leaving the issue open. Thanks for the response!

**Comment by leudz** [comment]
It'll be faster but you'd need a big number of components to really see the difference.
I assume the slowest part is updating the sparse array and the builtin implementation won't do much about it.

We'll see who implement it but I definitely won't close it until it's done.
Thank you for suggesting another cool feature!

**Comment by leudz** [comment]
Looking at this "a little" while later I think it should simply be a component.
A custom view if someone wants to go fancy.
