### ISSUE TITLE
Is There a Way to remove_component?

### ISSUE THREAD

**Issue by zicklag** [leudz/shipyard#98]
It feels like this should be in [EntitiesViewMut](https://docs.rs/shipyard/0.4.1/shipyard/struct.EntitiesViewMut.html), but I don't see anything.

**Comment by leudz** [comment]
You don't need the entities storage, technically you don't need it to add components either.
You can use the [`Remove`](https://docs.rs/shipyard/latest/shipyard/trait.Remove.html) or [`Delete`](https://docs.rs/shipyard/latest/shipyard/trait.Delete.html) trait based on what you want to do.
And here are the related chapters: [remove](https://leudz.github.io/shipyard/guide/fundamentals/remove-components.html) and [delete](https://leudz.github.io/shipyard/guide/fundamentals/delete-components.html).

**Comment by zicklag** [comment]
Ah, my bad. Thanks for the links. :slightly_smiling_face:
